docs/adr/0003-push-metrics-via-influxdb.md
docs/adr/index.md

@tordsson @llarsson @Xartos Seems like re-opening PRs to which one force-pushed is not legit with GitHub, so I'm forced to re-create a new PR.
Please review and let me know if you agree with the new wording.

Add push to influxdb adr

---

docs/operator-manual/clean-up.md
mkdocs.yml

Some short instructions on how to remove compliantkubernetes apps from a cluster.
Connected PR that contains the scripts: https://github.com/elastisys/compliantkubernetes-apps/pull/281

How to remove compliant kubernetes apps

---

docs/adr/0005-use-individual-ssh-keys.md
docs/ciso-guide/index.md

I made ADR-0005 vendor-neutral and transformed sentences that prescribed how the operations team should work into recommendations for operators. Let me know what you think about this format.

Make ADR-0005 vendor-neutral

---

docs/operator-manual/ovh-managed-kubernetes.md
mkdocs.yml

Title
fixes elastisys/compliantkubernetes-apps#192

Added docs for OVH managed kubernetes

---

docs/operator-manual/qa.md

Some intructions that I used for checking that some basic functioality works, like pushing and pulling images from harbor.
Don't really know where to put this.
I guess some other file has to be changed in order for this to be visible on the site.

Add sample qa instructions

---

docs/operator-manual/eksd.md

~~Putting this as a draft as i want to run through this again tomorrow.~~
Ran though it this morning and the instructions works fine.
**Tests**
Screenshot showing that collecting metrics and logs work, and that harbor is up and running
Note that I did not bother with OIDC, though the flags in the kube-apiserver was set.
Workload cluster
```ShellSession
❯ kubectl get all -A
NAMESPACE       NAME                                                                       READY   STATUS    RESTARTS   AGE
cert-manager    pod/cert-manager-756bb56c5-4sxzm                                           1/1     Running   0          12m
cert-manager    pod/cert-manager-cainjector-86bc6dc648-j7qnm                               1/1     Running   0          12m
cert-manager …
```

Add ck8s on AWS using EKS-D

---

docs/operator-manual/aws.md
docs/operator-manual/azure.md
docs/operator-manual/eksd.md
docs/operator-manual/exoscale.md
docs/operator-manual/ovh-managed-kubernetes.md

Removes the mention of an unused and removed configuration option.

Remove mention of objectStorage.s3.regionAddress

---

docs/operator-manual/disaster-recovery.md

Although I find this to be out of place, this is the artifact that was to be produced from this [issue](https://github.com/elastisys/compliantkubernetes-apps/issues/320)

Add initial obs provider feature matrix

---

docs/developer-guide/tech-radar/index.html
docs/developer-guide/tech-radar/radar.css
docs/developer-guide/tech-radar/radar.js
mkdocs.yml

As requested during the architecture meeting, I started working on a tech radar. It's meant to start an conversation and not be exhaustive. Nevertheless, I tried to put all tech I believe we will credibly use (or not use) within a year.
(Adding @lentzi90, since he was unhappy about having too few PRs to review this sprint. :smile:)

Add tech radar

---

README.md

Part of the "Developer experience" epic.

Add info on code snippets

---

docs/adr/0009-use-cluster-issuers-for-letsencrypt.md

This PR documents an architectural decision that is already implemented. It does not create any new action items, rather it ensures that we communicate both internally and externally a decision that we mindfully took.

ADR Use ClusterIssuers

---

docs/developer-guide/contributor-guide.md
mkdocs.yml

Added some sort of contributor guide.
Please check that this is what you wanted @cristiklein

Added contributor guide

---

docs/operator-manual/cluster-sizing.md
mkdocs.yml

Starting to document resource requirements of CK8s deployments

Add initial version of cluster sizing documentation

---

docs/faq.md

Customers asked "Will GrafanaLabs change to AGPL licenses affect the Compliant Kubernetes service somehow?", so it makes sense to publicly clarify. @tordsson , since you are the PM, please sign off.

Clarify Grafana AGPLv3

---

docs/operator-manual/troubleshooting.md

This PR adds a troubleshooting guide to help the distressed ops person.

Add troubleshooting

---

docs/operator-manual/aws.md

Clarify AWS cloud integration

---

docs/operator-manual/aws.md
docs/operator-manual/azure.md
docs/operator-manual/exoscale.md
docs/operator-manual/openstack.md

Updates to match https://github.com/elastisys/compliantkubernetes-kubespray/pull/94

Update doc to match upgrade to kubespray v2.16.0

---

docs/user-guide/harbor.md

This PR improves formatting of the Harbor docs and adds some explanation about Trivy capabilities.

Improve Harbor and Trivy docs

---

docs/adr/index.md

Required by our ISO certification process.

Write up architectural risk mitigation

---

docs/operator-manual/openstack.md

See PR in ck8s-kubespray: https://github.com/elastisys/compliantkubernetes-kubespray/pull/109
Issue: https://github.com/elastisys/compliantkubernetes-kubespray/issues/91
The LBaaS stuff is a bit awkward because this guide doesn't go through the apps setup, so I had to put some apps info in the kubespray section. Does it seem alright? I'm open for suggestions.

Update Openstack documentation to use external cloud controller

---

docs/release-notes.md
mkdocs.yml

This is the work on creating the user-facing release notes #148 .
Please let me know if the format works or if it should be changed or more simplified, and if I should add more/all versions to the list.

Add newest release notes

---

docs/operator-manual/disaster-recovery.md

Added some instructions on how to restore saved searches, dashboards, etc.

Add info on restoring kibana data

---

docs/compliance.md
docs/index.md

Take away FinTech regulations

---

docs/user-guide/kubernetes-api.md
user-demo/Dockerfile
user-demo/README.md

Part of the release process I have found some things that needed updating. 
The comment for USER in the dockerfile interfered with kubernetes.

user-demo: minor fixes

---

docs/user-guide/go-live.md
mkdocs.yml

First draft of go-live checklist

---

docs/compliantkubernetes/operator-manual/capacity-management.md
mkdocs.yml

@pettersv and (@simonekman, since we are a BizDevOps company :sunglasses:)
I felt inspired during my run and decided to upload the content of my brain to GitHub. :smile:
This document raises more questions than it brings answers, but I feel it is a good conversation starter. I would like to make this document public, for full transparency. I would also like to bring this document forward to the next available arch meeting (Nov 4th) to iron out the logic.
The document includes a recommendation to operators, but without taking a decision. @pettersv Can you spot it? :smile:

Add capacity management

---

docs/compliantkubernetes/adr/0012-do-not-persist-dex.md
docs/compliantkubernetes/adr/0017-persist-dex.md
docs/compliantkubernetes/adr/index.md

Veni, vidi, fixi
(As the Romans would say: I came, I saw, I fixed. :smile:)

ADR-0017 Persist Dex

---

docs/compliantkubernetes/office-hours.md
mkdocs.yml

Add office hours

---

docs/compliantkubernetes/operator-manual/maintenance.md

Added public facing maiteninace doc.

Add maintenace docs

---

overrides/main.html

Let's get this merged, mmkay? :D

Sets Matomo configuration for self-hosted instance

---

user-demo-dotnet/Program.cs
user-demo-dotnet/appsettings.Development.json
user-demo-dotnet/appsettings.json

Example of produced output:
```json
{"EventId":1,"LogLevel":"Information","Category":"Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware","Message":"Request:\nProtocol: HTTP/1.1\nMethod: GET\nScheme: http\nPathBase: \nPath: /\nAccept: */*\nHost: 172.17.0.2:3000\nUser-Agent: curl/7.68.0","State":{"Message":"Request:\nProtocol: HTTP/1.1\nMethod: GET\nScheme: http\nPathBase: \nPath: /\nAccept: */*\nHost: 172.17.0.2:3000\nUser-Agent: curl/7.68.0","Protocol":"HTTP/1.1","Method":"GET","Scheme":"http","PathBase":"","Path":"/","Accept":"*/*","Host":"172.17.0.2:3000","User-Agent":"curl/7.68.0"}}
{"EventId":2,"LogLevel":"Information","Category":"Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware","Message":"Response:\nStatusCode: 200\nContent-Type: application/json; charset=utf-8\nDate: …
```

Add structured logging for HTTP requests

---

docs/compliantkubernetes/user-guide/safeguards/enforce-trusted-registries.md

Add safeguard / enforce trusted registry

---

docs/compliantkubernetes/release-notes.md

Update release notes to include the patch version with the ODFE update.

apps release: ODFE update to 1.13.3

---

docs/compliantkubernetes/operator-manual/user-alerts.md
docs/compliantkubernetes/user-guide/alerts.md

In regards to moving it to an operator namespace as of elastisys/compliantkubernetes-apps#730.

Update docs on user alerting

---

docs/compliantkubernetes/user-guide/prepare.md

Recommend against PDB

---

docs/compliantkubernetes/user-guide/faq.md
docs/compliantkubernetes/user-guide/troubleshooting.md
mkdocs.yml

Add user-side FAQ and troubleshooting

---

docs/stylesheets/branding.css

Site header font set to 300 in font weight, and background to a slightly gray color instead of white.

Minor tweaks to background and header font

---

docs/compliantkubernetes/release-notes.md

Updated with the upcoming 0.19.
I've changed the format a little as there is quite a few big changes happening. Let me know what you think, and if I should update the old ones or if I should go back to the old format for this new entry.

Apps release v0.19.0

---

docs/compliantkubernetes/user-guide/faq.md

As requested during the retrospective.

Clarify ear

---

docs/compliantkubernetes/user-guide/logs.md

Clarify re-indexing

---

docs/compliantkubernetes/user-guide/go-live.md

Small reordering of the go-live checklist to better fit the process.

Reorder go-live checklist

---

docs/compliantkubernetes/operator-manual/disaster-recovery.md

Wrong config in opensearch disaster recovery

---

docs/compliantkubernetes/release-notes.md

Realized I forgot to update this during the last patch release.

Apps release notes v0.19.1

---

docs/compliantkubernetes/release-notes.md

Release notes for apps v0.20.0

docs:Apps v0.20.0 release notes

---

docs/compliantkubernetes/user-guide/network-model.md

Added comment to let the user know they can list ClusterIssuers and how.
Fixes : #321

docs: Added documentation on how to list ClusterIssuers

---

.github/workflows/lint.yml

Removed linting on pushes, now github will only do checks on pull requests.

Removed linting on pushes.

---

docs/compliantkubernetes/release-notes.md

Added release notes for kubespray v2.18.0-ck8s1

docs: Added release notes for kubespray v2.18.0-ck8s1

---

docs/compliantkubernetes/user-guide/delegation.md

Public Documentation for self-service User admin.
Fixes #[1749](https://github.com/elastisys/ck8s-ops/issues/1749) in ops-repo.

docs: added self-service delegation info

---

docs/compliantkubernetes/user-guide/network-model.md

Fixes #145 
Thanks for the tip @llarsson

Link to ahmetb's famous NetworkPolicy receipts

---

docs/compliantkubernetes/index.md
docs/compliantkubernetes/user-guide/prepare.md

docs: fix typos

---

docs/compliantkubernetes/release-notes.md

Added apps v0.22.0 release notes

Added apps v0.22.0 release notes

---

docs/compliantkubernetes/operator-manual/disaster-recovery.md

The documentation for how to restore services from off-site backups. And link to how to recover an encrypted off-site backup.

Add documentation to restore from off-site backups

---

docs/compliantkubernetes/adr/0015-we-believe-in-community-driven-open-source.md
docs/compliantkubernetes/adr/index.md
docs/compliantkubernetes/ciso-guide/audit-logs.md
docs/compliantkubernetes/ciso-guide/backup.md
docs/compliantkubernetes/ciso-guide/capacity-management.md
docs/compliantkubernetes/ciso-guide/controls.md
docs/compliantkubernetes/ciso-guide/cryptography.md
docs/compliantkubernetes/ciso-guide/intrusion-detection.md
docs/compliantkubernetes/ciso-guide/log-review.md
docs/compliantkubernetes/ciso-guide/network-security.md
docs/compliantkubernetes/ciso-guide/policy-as-code.md
docs/compliantkubernetes/ciso-guide/vulnerability.md
docs/compliantkubernetes/contributor-guide/index.md
docs/compliantkubernetes/operator-manual/disaster-recovery.md
docs/compliantkubernetes/operator-manual/maintenance.md
docs/compliantkubernetes/operator-manual/provider-audit.md
docs/compliantkubernetes/user-guide/alerts.md
docs/compliantkubernetes/user-guide/backup.md
docs/compliantkubernetes/user-guide/delegation.md
docs/compliantkubernetes/user-guide/logs.md
docs/compliantkubernetes/user-guide/metrics.md
docs/compliantkubernetes/user-guide/network-model.md
docs/compliantkubernetes/user-guide/prepare-application.md
docs/compliantkubernetes/user-guide/safeguards/enforce-networkpolicies.md
docs/compliantkubernetes/user-guide/safeguards/enforce-no-root.md
docs/compliantkubernetes/user-guide/safeguards/enforce-resources.md
docs/compliantkubernetes/user-guide/safeguards/enforce-trusted-registries.md
mkdocs.yml

@simonekman !!! It's been a while since you reviewed a PR. :smile:
I've been meaning to do this for a while, thanks for your push.
The screenshot below shows the result after merging this PR.
Let me know what you think.

Organize by controls

---

docs/compliantkubernetes/ciso-guide/controls.md
mkdocs.yml

Follow-up from previous PR, added controls outside the scope of BSI IT-Grundschutz.

Add bsi controls

---

docs/compliantkubernetes/operator-manual/provider-audit.md

New point for checking with new providers if they support multiple projects per user.

Added a new point in the IAM provider audit

---

docs/compliantkubernetes/release-notes.md

docs: apps v0.23 release notes

---

docs/compliantkubernetes/release-notes.md

Release notes for apps v0.24.0

docs: updated release notes for apps v0.24.0

---

docs/compliantkubernetes/release-notes.md

updated release notes for patch v0.24.1

docs: updated release notes for patch v0.24.1

---

docs/compliantkubernetes/release-notes.md

Added release notes for apps v0.25.0

added release notes for apps v25

---

docs/compliantkubernetes/user-guide/network-model.md

Is this what application developers asked for?

Clarify how to use application CNAMEs

---

docs/compliantkubernetes/operator-manual/disaster-recovery.md

This documentation is not true anymore.

docs: remove outdated grafana restore docs

---

docs/user-guide/ci-cd.md
mkdocs.yml

Recently helped a customer install ArgoCD and found some stuff that would be helpful to both the user and administrator.

docs: updated cicd page about argocd

---

docs/operator-manual/access-control.md

https://github.com/elastisys/compliantkubernetes-apps/pull/1160

Remove metion of readall_and_monitor

---

docs/user-guide/metrics.md

https://github.com/elastisys/compliantkubernetes-apps/pull/1163

Update prometheus UI access

---

docs/tech-radar/index.html

Updated tech radar to capture recent discussions and decisions taken during the arch meeting.
To facilitate reviewing, I'm attaching the resulting tech radar below:

Update tech radar

---

mkdocs.yml

Couldn't access this page via the navbar

docs: fix broken page

---

docs/operator-manual/disaster-recovery.md

https://github.com/elastisys/compliantkubernetes/issues/391

docs: set opensearch dr user

---

docs/release-notes/rabbitmq.md

docs: rabbit-mq release notes v3.10.7

docs: rabbit-mq release notes v3.10.7

---

docs/release-notes/rabbitmq.md

Fix release notes 

---

user-demo/README.md
user-demo/app.js
user-demo/docker-compose.yaml
user-demo/package-lock.json
user-demo/package.json
user-demo/scripts/run-locally.sh
user-demo/tracing.js

added support for tracing and Jaeger

user-demo: added distributed tracing and Jaeger

---

docs/user-guide/setup.md

Follow-up to [your comment](https://github.com/elastisys/compliantkubernetes/pull/408#issuecomment-1253473490).

Recommend OpenLens on the prepare page

---

docs/operator-manual/disaster-recovery.md

Made some clarifications (hopefully) on how to restore Opensearch dashboards data. Fixes #392

docs: updated DR guide for opensearch dashboards

---

docs/release-notes/rabbitmq.md

I thought this could use an improvement and some additional information about the new version.

Update RabbitMQ release notes

---

docs/operator-manual/disaster-recovery.md

https://github.com/elastisys/compliantkubernetes/issues/390

docs: when a new region/cloud provider is used

---

docs/release-notes/redis.md

redis-release-notes

---

docs/user-guide/safeguards/enforce-no-latest-tag.md
mkdocs.yml

docs: enforce no latest tag

---

docs/operator-manual/break-glass.md

This is a draft for break-the-glass section.  I m not quite sure if this is what we want to have here. Please go through it and have your say.

Document for breaking the glass

---

docs/release-notes/ck8s.md

Release notes for compliantkubernetes-apps patch v0.26.2

docs: Release notes for compliantkubernetes-apps patch v0.26.2

---

docs/adr/0024-allow-Harbor-robot-account.md
docs/adr/index.md

ADR: Create a Harbor robot account

adr:Create a Harbor robot account

---

docs/adr/0025-local-storage.md
docs/adr/index.md

ADR: Local storage for Managed Services that requires high speed performance disks.

adr:Local storage for services that requires high speed disks

---

mkdocs.yml

Ensure that the 'edit' button works correctly.

Fix repo_url

---

docs/adr/0026-hnc.md
docs/adr/index.md

adr:Hierarchical Namespaces

---

docs/user-guide/alerts.md
docs/user-guide/metrics.md

Update metrics and metrics alerting

---

docs/release-notes/ck8s.md

docs: added release notes for apps v0.27

---

docs/user-guide/additional-services/redis.md

Since we are using a config map for this data we should update the public docs to match

Updated redis access from secret to configmap

---

docs/release-notes/redis.md

Redis v1.1.1-ck8s4

---

docs/adr/0028-harder-pod-eviction-when-node-goes-OOM.md
docs/adr/index.md

ADR: Harder pod eviction when node goes oom

adr: Harder pod eviction when node goes oom

---

docs/operator-manual/on-prem-standard.md

Hi!
I'm sending this PR for review to the whole on-prem team for awareness.
/Cristian

Link to blog post explaining IDP setup

---

docs/user-guide/faq.md
docs/user-guide/namespaces.md
mkdocs.yml

docs: made a separate page for namespaces

---

docs/operator-manual/maintenance.md

I have the feeling that we are presenting the information twice.
As most of the steps for upgrading apps or kubespray are present in the migration guides.
Let me know what you think. 
issue #475

added: maintenance checklist

---

docs/adr/0030-run-argocd-on-elastisys-nodes.md
docs/adr/index.md
overrides/partials/source.html

adr0030 Run ArgoCD on the Elastisys nodes

adr: run argocd on elastisys nodes

---

docs/ciso-guide/audit-logs.md
docs/ciso-guide/backup.md
docs/ciso-guide/controls/_common.include
docs/ciso-guide/controls/hslf-fs-201640.md
docs/ciso-guide/cryptography.md
docs/ciso-guide/log-review.md
docs/operator-manual/access-control.md
docs/operator-manual/credentials.md
docs/operator-manual/disaster-recovery.md
docs/operator-manual/provider-audit.md
docs/user-guide/backup.md
docs/user-guide/demarcation.md
docs/user-guide/how-many-environments.md
docs/user-guide/kubernetes-api.md
docs/user-guide/network-model.md

Some parts of HSLF-FS are more prescriptive. Let's highlight them more.

Map HSLF-FS 2016:40

---

mkdocs.yml

Jaeger-docs fix

---

docs/adr/0031-run-csi-cinder-controllerplugin-on-elastisys-nodes.md
docs/adr/index.md

Run the csi-cinder-controllerplugin on the Elastisys nodes

adr: Run the csi-cinder-controllerplugin on the Elastisys nodes

---

docs/operator-manual/disaster-recovery.md

As per DR activities and discussed during DR , updated the Velero command .

Updated Velero backup commands

---

docs/operator-manual/provider-audit.md

Add evidence gathering

---

docs/user-guide/network-model.md
mkdocs.yml

Add details regarding letsencrypt issuers

---

docs/user-guide/safeguards/enforce-networkpolicies.md
docs/user-guide/safeguards/enforce-no-latest-tag.md
docs/user-guide/safeguards/enforce-resources.md
docs/user-guide/safeguards/enforce-trusted-registries.md

With relation to this [PR](https://github.com/elastisys/compliantkubernetes-apps/pull/1426)

docs: Updated Gatekeeper default enforcements

---

docs/user-guide/additional-services/rabbitmq.md

Some info in how to more effectively use RabbitMQ and making it clear that quorum queues are the way to go for HA.

Add RabbitMQ best practices

---

docs/release-notes/ck8s.md

docs: add release notes for apps v0.28.1

docs: add release notes for apps v0.28.1 - release 

---

docs/user-guide/demarcation.md

Something like this @pettersv ?

Add TL;DR of demarcation

---

docs/release-notes/jaeger.md
mkdocs.yml

added the first jaeger release. Hopefully now it will be visible on the public docs

added: first jaeger release

---

docs/adr/0033-run-cluster-api-controllers-on-service-cluster.md
docs/adr/index.md

I hope this is good enough :sweat_smile:
The Tekton ADR will follow as it builds on this basically.

adr: Run Cluster API controllers on Service Cluster

---

docs/adr/0035-run-tekton-on-service-cluster.md
docs/adr/index.md

adr: Run Tekton on service cluster

---

docs/operator-manual/provider-audit.md

Added Environment management questions to the provider audit, as asked by @henberg . Screenshot of the result is below:

Add Environment Management to provider audit

---

mkdocs.yml

Add link to Training

---

docs/operator-manual/cluster-sizing.md
docs/operator-manual/credentials.md
docs/user-guide/metrics.md

Replace InfluxDB with Thanos on Cluster Sizing page

Replace InfluxDB with Thanos on Cluster Sizing page

---

docs/user-guide/faq.md

Removed an old question and added one that is still relevant.

docs: update user faq page

---

docs/adr/0038-replace-starboard-operator-with-trivy-operator.md
docs/adr/index.md

Replace starboard-operator with trivy-operator

adr: replace starboard-operator with trivy-operator

---

docs/ciso-guide/log-review.md
docs/operator-manual/access-control.md
docs/operator-manual/disaster-recovery.md
docs/user-guide/delegation.md
docs/user-guide/kubernetes-api.md
docs/user-guide/logs.md

Deleted some notices about ElasticSearch that are no longer in this project and fixed a typo that was made.
Fixes issue #507

docs: Deleted some notes about ElasticSearch and fixed a typo.

---

docs/user-guide/additional-services/redis.md

Added Best practices recommended when customer starts using Redis.

Added Redis Best practices recommended

---

docs/user-guide/demarcation.md

Clarify demarcation

---

docs/user-guide/additional-services/redis.md

As discussed yesterday mini-ADR - https://github.com/elastisys/ck8s-arch/issues/18  , added note to it.

Updated the redis best prac

---

docs/adr/0037-enforce-ttl-on-jobs.md
docs/adr/index.md

adr: enforce ttl on jobs

---

docs/user-guide/additional-services/ferretdb.md
mkdocs.yml

Issue: #569 
Document how to setup FerretDB for application developers using Compliant Kubernetes.

Added FerretDB documentation.

---

docs/operator-manual/provider-audit.md

Improve the question on physical security, by specifically asking for skyddsklass 3, a standard developed by SSF and recommended by MSB.

Improve question on skyddsklass 3

---

docs/operator-manual/disaster-recovery.md

Added a note on what to expect when we recover the environment but with a new domain name.

Update DR with a note on ingresses and image ids

---

docs/release-notes/jaeger.md

Added the release notes for Jaeger v1.39.0-ck8s2

jaeger: release notes for v1.39.0-ck8s2

---

docs/operator-manual/disaster-recovery.md

#493 
Added the pattern necessary to restore opensearch with index per namespace

added: dr docs index per namespace restore pattern

---

docs/release-notes/rabbitmq.md

Rabbitmq v3.11.18 release note

Rabbitmq v3.11.18 release note

---

docs/adr/0041-encryption-at-rest.md
docs/adr/0042-argocd-dynamic-hnc-namespaces.md
docs/adr/index.md

ADR for ArgoCD dynamic HNC namespaces.

ADR for ArgoCD dynamic namespaces using HNC

---

docs/release-notes/ck8s.md

release: added the release notes for apps v0.31

---

docs/operator-manual/on-prem-standard.md

Fixed some spelling errors, fixed indentation, added installation of kubespray pre-requisites, removed the usage of sops with kubeconfig as we usually use OIDC authentication (added a note in the case of using sops encrypted kubeconfigs).

Various fixes to on-prem standard template

---

docs/adr/0042-argocd-dynamic-hnc-namespaces.md
docs/user-guide/additional-services/argocd.md

Specifically:
- Harmonize with our Glossary
- Capitalize Kubernetes concepts
- Link to the ADR from the Argo CD user-guide
- Improve the flow of some sentences

Polish ADR-0042

---

docs/release-notes/jaeger.md

Added release notes for the latest patch release

docs: added release notes for jaeger v1.39.0-ck8s3

---

docs/adr/0043-rclone-and-encryption-adhere-cryptography-policy.md
docs/adr/index.md

ADR for Rclone and Encryption adheres Cryptography Policy based on discussion during architecture meeting - https://github.com/elastisys/ck8s-arch/issues/10

ADR: Rclone and Encryption adheres Cryptography Policy

---

docs/user-guide/registry.md

Added a short presentation about the retention rules in Harbor and where to find the details on how to set it
As the process is quite complex and long I didn't want to duplicate the upstream docs, but let me know if you think I should add more details.

WIP harbor docs: tag retention rules

---

docs/user-guide/safeguards/enforce-podsecuritypolicies.md
mkdocs.yml

Since we haven't added anything regarding this and it may be good information for app devs to know.

Document restricted privileges safeguard

---

docs/ciso-guide/controls/mdr.md
docs/user-guide/how-many-environments.md
mkdocs.yml

As discussed during the Product Management meeting.

Add MDR controls

---

.pre-commit-config.yaml
docs/adr/0034-how-to-run-multiple-ams-packages-of-the-same-type.md
docs/adr/0042-argocd-dynamic-hnc-namespaces.md
docs/contributor-guide/index.md

Enforce capitalization of Compliant Kubernetes

---

mkdocs.yml

I just noticed that we missed some trademark in our notice.

Add more trademark notices

---

docs/index.md
docs/operator-manual/index.md
docs/operator-manual/on-prem-standard.md
extra_sass/style.css.scss

Inspired by @emmasundqvist , I decided to improve the landing page for platform administrators.
This is not the final story, just an improvement over what we previously had.
Let me know what you think.

Improve admin landing page

---

docs/index.md
extra_sass/style.css.scss

Bring back the left navbar and the right toc.
Fixes #674

Bring back the left navbar

---

docs/index.md

Fixed improve statement issue (#675)

---

docs/release-notes/ck8s.md

Added release notes for apps v0.33.0

---

.github/workflows/lint.yml

Test to avoid re-occurance of https://github.com/elastisys/compliantkubernetes/commit/29db0d854d64ff488c53a222b073203816940fc3

Test for stranded html tags

---

docs/user-guide/additional-services/jaeger.md

Added jaeger-agent deprecation note

Added jaeger-agent deprecation note

---

.gitignore
docs/user-guide/additional-services/redis.md

Redis NetworkPolicy labeling

---

docs/user-guide/long-term-log-retention.md

Correctly state retention of logs

---

docs/adr/0011-let-upstream-projects-handle-crds.md

Fix 404 link to upgrading with helm

---

docs/glossary.md

Fixes #696
Same URL as in da49c886d8b890ee31711a87a4f489f6a6ef810a but in a different section.

Fix another instance of 403 to EDPB website

---

docs/operator-manual/qa.md

I'm capturing here the outcome of a Slack conversation we had about an upcoming AMS. We are missing some quality criteria which are really important for product.

Add quality criteria for application developers

---

docs/operator-manual/provider-audit.md

Audit: Are colocation providers subprocessors?

---

.codespellignore
docs/ciso-guide/controls/kritis.md
docs/ciso-guide/controls/msbfs-20188.md
mkdocs.yml

Reorg regulations

---

docs/ciso-guide/controls/mdr.md

Improve MDR page based on customer feedback

---

docs/index.md

Add missing registered trademark

---

docs/release-notes/kubespray.md

docs: Update release notes for kubespray

---

docs/release-notes/ck8s.md

add: release notes for v0.32.2

---

docs/release-notes/ck8s.md

add: release notes for v0.33.1 and v0.32.2

---

docs/release-notes/kubespray.md

Updated link to kubespray release

---

docs/operator-manual/common.md
docs/operator-manual/getting-started.md
docs/operator-manual/on-prem-standard.md

Add operate section to on-prem template

---

docs/release-notes/argocd.md

docs: Release notes for Argo CD v2.7.14

---

docs/user-guide/self-managed-services/flux.md
docs/user-guide/self-managed-services/mongodb.md
docs/user-guide/self-managed-services/sealedsecrets.md

docs: define supported CRD and operator versions

---

docs/operator-manual/provider-audit.md

Add question on pen-test

---

docs/adr/0044-argocd-managing-its-own-namespace.md
docs/adr/index.md

adr: argocd does not manage its own namespace

---

requirements.txt

set fixed mike version to avoid conflict

---

docs/user-guide/backup.md

Clarify backup retention

---

docs/release-notes/ck8s.md

docs: Updates release notes for app v0.34

---

docs/adr/0039-application-dev-permissions.md
docs/adr/index.md

adr-0039: app dev privilege elevation

---

.pre-commit-config.yaml
docs/ciso-guide/index.md
docs/index.md
docs/operator-manual/index.md

Improve pagespeed insights

---

docs/operator-manual/troubleshooting.md
docs/stylesheets/extra.css

This PR:
1. introduces the `elastisys-self-managed` admonition;
2. gives an example of how to use the `elastisys-self-managed` admonition; and
3. fixes the contrast in the `elastisys` admonition.

Elastisys self managed admonition

---

docs/user-guide/additional-services/argocd.md

Add docs for Argo CD notifications

---

docs/operator-manual/provider-audit.md

SME: Mark less relevant provider audit questions

---

docs/release-notes/ck8s.md

release: added release notes for v0.35

---

.editorconfig
.eslintrc.yml
.pre-commit-config.yaml
docs/javascripts/feedback.js
mkdocs.yml

This PR adds a "Was this page helpful?" question at the very bottom of each page. The information is sent to Matomo via the [Event Tracking API](https://matomo.org/faq/reports/implement-event-tracking-with-matomo/#how-to-set-up-matomo-event-tracking-with-javascript).

Add "Was this page helpful?"

---

docs/release-notes/ck8s.md

Added release notes for v0.34.1

---

docs/glossary.md

"Environment is compose of" -> "Environment is composed of"

Fix a typo in glossary

---

mkdocs.yml

Updated site description

---

mkdocs.yml

Shorten site description

---

docs/release-notes/ck8s.md

Added release notes for Apps v0.35.1

---

docs/release-notes/ck8s.md

 Added release notes for Apps v0.35.1 

---

docs/release-notes/ck8s.md

Added release notes for Apps v0.34.2

---

docs/user-guide/additional-services/rabbitmq.md

A little fix for actually using the variables we say to get.

Use variables for RabbitMQ default user secret

---

docs/release-notes/rabbitmq.md

Added release notes for rabbitmq v3.12.6-ck8s1

---

docs/release-notes/kubespray.md

Added release nodes from kubespray v2.23.0-ck8s2

---

docs/adr/0022-use-dedicated-nodes-for-additional-services.md
docs/adr/index.md
docs/architecture.md
docs/ciso-guide/audit-logs.md
docs/ciso-guide/controls/nist-sp-800-171.md
docs/ciso-guide/intrusion-detection.md
docs/ciso-guide/log-review.md
docs/ciso-guide/vulnerability.md
docs/operator-manual/clock-synchronization.md
docs/operator-manual/cryptography.md
docs/operator-manual/disaster-recovery.md
docs/operator-manual/maintenance.md
docs/operator-manual/provider-audit.md
docs/user-guide/ci-cd.md
docs/user-guide/delegation.md
docs/user-guide/demarcation.md
docs/user-guide/how-many-environments.md
docs/user-guide/kubernetes-api.md
docs/user-guide/logs.md
docs/user-guide/metrics.md
docs/user-guide/network-model.md
docs/user-guide/prepare-idp.md
docs/user-guide/registry.md
docs/user-guide/safeguards/enforce-no-root.md
docs/user-guide/safeguards/enforce-podsecuritypolicies.md
docs/user-guide/safeguards/enforce-trusted-registries.md
mkdocs.yml

Add mapping to NIST SP 800-171 Requirements

---

docs/release-notes/capi.md
mkdocs.yml

add changelog for cluster api

---

docs/release-notes/ck8s.md

release: added release notes for v0.36

---

docs/release-notes/kubespray.md

docs: Added release notes for kubespray v2.24.1-ck8s1

---

docs/adr/0008-use-hostnetwork-or-loadbalancer-for-ingress.md
docs/adr/0009-use-cluster-issuers-for-letsencrypt.md
docs/adr/index.md
docs/operator-manual/air-gapped-environment.md
docs/operator-manual/common.md
docs/operator-manual/provider-audit.md
docs/release-notes/ck8s.md
docs/user-guide/backup.md
docs/user-guide/continous-development.md
docs/user-guide/delegation.md
docs/user-guide/demarcation.md
docs/user-guide/deploy.md
docs/user-guide/kubernetes-api.md
docs/user-guide/logs.md
docs/user-guide/long-term-log-retention.md
docs/user-guide/metrics.md
docs/user-guide/namespaces.md
docs/user-guide/network-model.md
docs/user-guide/operate.md
docs/user-guide/prepare-idp.md
docs/user-guide/safeguards/enforce-networkpolicies.md
docs/user-guide/safeguards/enforce-no-latest-tag.md
docs/user-guide/safeguards/enforce-podsecuritypolicies.md
docs/user-guide/safeguards/enforce-resources.md
docs/user-guide/safeguards/enforce-trusted-registries.md

If there is anything here you think should not have been changed do tell and the same if you you know some other typo in the docs that I can put in this pr.
Since this type of [PodSecurityPolicies](https://kubernetes.io/docs/concepts/security/pod-security-policy/) is no longer available the [text](https://elastisys.io/compliantkubernetes/user-guide/demarcation/#specifics) should be changed but I don't know what to change it to, so i would like suggestions.
If no suggestions gets added I will just not change anything with text.

minor grammar corrections

---

docs/user-guide/how-many-environments.md

Add concept of Application Deployments and describe levels of isolations when discussing how many Environments should be used

docs: Application Deployments and Isolations Levels

---

docs/user-guide/safeguards/enforce-no-load-balancer-service.md
mkdocs.yml

Public documentation part of https://github.com/elastisys/compliantkubernetes-apps/pull/1924

Document LoadBalancer Service safeguard

---

docs/operator-manual/capacity-management.md
docs/operator-manual/troubleshooting.md

Part of this [issue](https://github.com/elastisys/compliantkubernetes-apps/issues/1864) and [PR](https://github.com/elastisys/compliantkubernetes-apps/pull/1988)

docs: update capacity management page after rework

---

docs/operator-manual/capacity-management.md

docs: add section about node groups

---

docs/release-notes/kubespray.md

kubespray: Release v2.23.0-ck8s3

---

docs/release-notes/argocd.md

docs: Update release the notes for ArgoCD v2.9.5-ck8s1

---

.github/workflows/checklinks.yml
docs/adr/0021-tls-for-additional-services.md
docs/operator-manual/disaster-recovery.md
docs/user-guide/additional-services/index.md
docs/user-guide/alerts.md
docs/user-guide/ci-cd.md
docs/user-guide/delegation.md
docs/user-guide/log-based-alerts.md
docs/user-guide/prepare.md
docs/user-guide/safeguards/enforce-resources.md
linkchecker-with-anchorcheck.conf

A few anchors were broken, in particular towards the ToS. This happened because we changed the heading of the ToS and their anchors are generated by `slugify`-ing them.
This PR tests anchors to make sure we can detect and fix them in the future.

Enable anchorcheck

---

docs/user-guide/namespaces.md

Documentation for [this feature](https://github.com/elastisys/compliantkubernetes-apps/pull/1842)

docs: add section for hnc opt-in propagation

---

.github/pull_request_template.md
docs/glossary.md

Add quality gates

---

user-demo/deploy/ck8s-user-demo/templates/ingress.yaml
user-demo/deploy/ck8s-user-demo/values.yaml

Quality gates:
Reason:
As this is the recommended way of doing it these days, I thought I'd update this while I still remember :smile:

config: use ingressClassName in user demo

---

docs/user-guide/additional-services/argocd.md

Quality gates:
This currently links to a ToS appendix where ArgoCD is not mentioned yet, this will be updated later by @cristiklein .
If I understand correctly, the preview feature part will be removed in near future as well?
- Closes elastisys/ck8s-argocd#128

docs: elastisys admonition for argocd

---

docs/user-guide/additional-services/argocd.md

docs: removed argocd rpo of 1 day

---

docs/index.md

Rename support to self-managed

---

docs/user-guide/additional-services/timescaledb.md

Clarification on the application developer docs about which edition of features we use and why.

docs: timescaledb edition clarification

---

docs/quality-criteria.md
mkdocs.yml

This page doesn't really talk about quality assurance, rather about quality criteria which are taken into account when designing a new features.
Quality gates:
Related to #818

Cleanup quality criteria

---

docs/release-notes/argocd.md

Add release notes for ArgoCD v2.9.9

---

docs/mission-and-vision.md
mkdocs.yml

Quality gates:
As far as I can tell, this version addresses all feedback we received during the arch meeting. PTAL.

Add mission and vision

---

docs/user-guide/additional-services/argocd.md

Quality gates:
- Fixes https://github.com/elastisys/ck8s-argocd/issues/157

docs: argocd vals with vault

---

docs/operator-manual/disaster-recovery.md

Quality gates:
Updates the restore docs to point to the new docs in Apps.
Also remove the version note because it has been a standard feature for _quite_ a long time.

Update rclone restore docs

---

docs/operator-manual/troubleshooting.md

Added diagnostics command info

---

docs/release-notes/ck8s.md

apps: added v0.37 release notes

---

docs/operator-manual/provider-audit.md

Quality gates:
Ask for support for the Snapshot feature as part of the provider audit. The Snapshot feature enables more consistent Velero backups.

Add question on Snapshot feature

---

docs/glossary.md

Quality gates:
We decided to add some frequently-used legal terms to the Compliant Kubernetes glossary.

Add legal terms to glossary

---

docs/ciso-guide/isa-iec-62443.md
docs/user-guide/delegation.md
mkdocs.yml

Add ISA/IEC 62443

---

mkdocs.yml

Quality gates:
Part of #844 
I checked and the text fits in the social cards. Attaching a few as evidence:

Update site description

---

docs/release-notes/jaeger.md

jaeger: added v1.52.0-ck8s1 release notes

---

docs/user-guide/additional-services/argocd.md

Quality gates:
- Fixes elastisys/ck8s-argocd#125

argocd: added a restrictions section

---

.pre-commit-config.yaml
docs/release-notes/redis.md

redis: added v6.2.6-ck8s4 release notes

---

docs/ciso-guide/log-review.md

docs: typo in log-review page

---

docs/operator-manual/disaster-recovery.md

docs: update velero restore commands to be more consistent

---

docs/operator-manual/provider-audit.md

Fix: indenting issues in provider-audit

---

.github/workflows/lint.yml

Quality gates:
I forgot one thing :sweat_smile:

pre-commit: Disable commit-to-branch in workflow

---

docs/user-guide/metrics.md

docs: Add section about wc prometheus access

---

docs/mission-and-vision.md
docs/operator-manual/disaster-recovery.md

Quality gates:
Fixing [#63](https://github.com/elastisys/mse-internal-docs/issues/63) 
Note:
Under construction. Somehow it would be cool if an example scenario could be presented with commands serving to solve the given issue

docs: update velero disaster restoration & backup docs

---

docs/user-guide/safeguards/enforce-minimum-replicas.md
mkdocs.yml

document minumum replicas constraint

---

docs/mission-and-vision.md

Quality gates:
Fixes issues that was previously merged.

Run pre-commit

---

linkchecker.conf

To avoid false positives. We want to know if our links are broken, not if a website is down.
Quality gates:

Filter more errors

---

docs/user-guide/additional-services/argocd.md

docs: argocd dex oath invalid credentials

---

docs/user-guide/faq.md

Quality gates:
Adds a subsection in the user-guide/faq discussing why and how grafana can OOM kill and what to do about it.
Fixes: #[272](https://github.com/elastisys/ck8s-issue-tracker/issues/272)

docs: add faq about grafana OOM

---

.gitignore

Quality gates:
Ignore .DS_Store (mac thing), will have to add this to more repositories 😄

Added .DS_Store to gitignore

---

docs/release-notes/ck8s.md

apps: added v0.38.0 release notes

---

docs/user-guide/namespaces.md

Quality gates:
I felt there was a need to add how to delete the subnamespace resource so I added it in this PR.

hnc how to delete subnamespaces

---

mkdocs.yml
requirements.txt

Quality gates:
Various fixes to improve the quality of documentation generation.

Various fixes 2

---

README.md

Quality gates:
Added a note that cairo might have to be installed for Mac users, since it is required to run locally.

added a note about cairo under usage

---

docs/user-guide/prepare-idp.md

docs: update Azure AD to Microsoft Entra ID in idp page

---

docs/user-guide/kubernetes-api.md

docs: minor fix for kubernetes-api page

---

docs/user-guide/logs.md
docs/user-guide/long-term-log-retention.md

docs: updates/fixes for logging and long-term log retention pages

---

docs/user-guide/alerts.md
docs/user-guide/metrics.md

docs: minor changes to metrics page and alerts page

---

docs/user-guide/maintenance.md

docs: minor fixes for maintenance page

---

mkdocs.yml

Testing disabling strict mode

---

.github/workflows/deploy.yml
mkdocs.yml

testing --allow-empty flag for mike

---

.github/workflows/deploy.yml
requirements.txt

reverting back to old mike version

---

docs/user-guide/demarcation.md

docs: fixes for demarcation page

---

docs/user-guide/delegation.md

docs: fixes for delegation page

---

docs/user-guide/cluster-api.md

docs: minor fixes for capi page

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/operator-manual/provider-audit.md

Also used this opportunity to make it "vale-proof", i.e., ensure that spelling, terminology and grammar can be checked programatically.
Quality gates:

Add questions to provider audit

---

.vale.ini
ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/operator-manual/capacity-management.md

Also performed some vale cleanup as part of this PR.
Quality gates:

Improve capacity management page

---

docs/adr/0048-access-management-for-AMS-with-network-policies.md
docs/adr/index.md

adr-0048: Access Management for Additional Managed Services (AMS-es)

---

docs/user-guide/delegation.md
docs/user-guide/metrics.md

Mention Grafana allowedDomains in User Guide

---

docs/adr/0049-run-ingress-nginx-in-chroot.md
docs/adr/index.md

adr-0049-run-ingress-nginx-in-chroot

---

docs/user-guide/network-model.md

Quality gates:
As a result of recent arch topic discussion: https://github.com/elastisys/ck8s-arch/issues/182.

Warning about DNS-01 issuer and certificate monitoring tip

---

docs/release-notes/ck8s.md

Add changelog for Apps v0.38.1

---

docs/release-notes/ck8s.md

Add release notes for Apps v0.39.0

---

docs/release-notes/ck8s.md

Add release notes for Apps v0.38.2

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/ciso-guide/information-security/dod-enterprise-devsecops-reference-design-kubernetes.md

Minor fixes

---

docs/release-notes/capi.md

release: capi v0.2.0

---

CONTRIBUTING.md
docs/operator-manual/common.md
docs/operator-manual/on-prem-standard.md

Quality gates:
Updated the documentation for running `ck8s init` with the new `CK8S_K8S_INSTALLER` variable (see [this PR](https://github.com/elastisys/compliantkubernetes-apps/pull/2190)). Also updated some alerts to use github-style since that was the recommended way in our contributing guide.

Update ck8s deploy docs with new ck8s config variable

---

.github/pull_request_template.md
docs/operator-manual/common.md
docs/operator-manual/getting-started.md
docs/operator-manual/index.md
docs/operator-manual/on-prem-standard.md
docs/user-guide/additional-services/argocd.md
docs/user-guide/additional-services/index.md
docs/user-guide/additional-services/postgresql.md
docs/user-guide/additional-services/rabbitmq.md
docs/user-guide/self-managed-services/_common-crds.include
docs/user-guide/self-managed-services/ferretdb.md
docs/user-guide/self-managed-services/flux.md
docs/user-guide/self-managed-services/jupyterhub.md
docs/user-guide/self-managed-services/kafka.md
docs/user-guide/self-managed-services/mongodb.md
docs/user-guide/self-managed-services/sealedsecrets.md
docs/user-guide/self-managed-services/sjunet.md

Quality gates:
I was reading some of our documentation and correcting some grammar, and other small things as I went.
If you want an explanation on a specific part, just ask and I will explain my though process on it.

docs: adjusted some pages 

---

docs/operator-manual/clock-synchronization.md

docs: clarify use of clock synchronization

---

docs/release-notes/kubespray.md

docs: Add release notes for v2.24.1-ck8s1 and v2.24.1-ck8s2

---

docs/release-notes/kubespray.md

docs: add release notes for kubespray v2.25.0-ck8s1

---

docs/user-guide/logs.md

docs: add how to index unindexed opensearch fields

---

docs/release-notes/ck8s.md

docs: added release notes for apps v0.39.1

---

docs/release-notes/kubespray.md

release: Added release notes for kubespray patches

---

docs/stylesheets/branding.css

Make code more readable

---

docs/operator-manual/common.md

Quality gates:
- Part of https://github.com/elastisys/compliantkubernetes-apps/issues/2154

docs: update ck8s diagnostics command usage

---

docs/release-notes/ck8s.md

Added v0.40.0 to ck8s release notes

---

docs/release-notes/capi.md

release: capi v0.3.0

---

docs/release-notes/ck8s.md

Add release notes for Apps v0.39.2 to main

---

docs/release-notes/ck8s.md

Add release notes for Apps v0.39.2

---

docs/release-notes/kubespray.md

docs: add release notes for kubespray v2.25.0-ck8s4

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/ciso-guide/controls/nis2.md
docs/ciso-guide/index.md
docs/ciso-guide/vulnerability.md
docs/operator-manual/access-control.md
docs/operator-manual/cryptography.md
docs/operator-manual/disaster-recovery.md
docs/operator-manual/provider-audit.md
docs/operator-manual/troubleshooting.md
docs/user-guide/alerts.md
docs/user-guide/backup.md
docs/user-guide/delegation.md
docs/user-guide/demarcation.md
docs/user-guide/how-many-environments.md
docs/user-guide/log-based-alerts.md
docs/user-guide/network-model.md
docs/user-guide/prepare-idp.md
docs/user-guide/troubleshooting.md
mkdocs.yml

Hi folks,
I want to challenge a bit the statement that NIS2 Minimum Requirements are so vague that a mapping to Compliant Kubernetes features is not useful. To that end, I went ahead and mapped the NIS2 Minimum Requirements to Compliant Kubernetes features. :joy:
See screenshot below.
Let me know what you think.
Quality gates:

Add NIS2 Minimum Requirements

---

docs/user-guide/self-managed-services/_common.include

Make it clear that we don't keep these pages up-to-date.
Quality gates:

Add self-managed apps disclaimer

---

docs/user-guide/additional-services/postgresql.md

Quality gates:
Wasn't 100% sure where to add this information, let me know what you think.

docs: postgres pdb

---

docs/adr/0052-azure-encryption-at-rest.md
docs/adr/index.md

adr:0052 Azure Encryption-at-Rest for Object Storage and Block Storage

---

docs/user-guide/safeguards/enforce-job-ttl.md
docs/user-guide/safeguards/enforce-minimum-replicas.md
docs/user-guide/safeguards/enforce-networkpolicies.md
docs/user-guide/safeguards/enforce-no-latest-tag.md
docs/user-guide/safeguards/enforce-no-load-balancer-service.md
docs/user-guide/safeguards/enforce-no-root.md
docs/user-guide/safeguards/enforce-podsecuritypolicies.md
docs/user-guide/safeguards/enforce-resources.md
docs/user-guide/safeguards/enforce-trusted-registries.md
docs/user-guide/safeguards/index.md

Quality gates:
I tried to do some clarifications and standardization of the safeguard pages.

docs: safeguard improvements

---

docs/release-notes/ck8s.md

docs: add release notes for v0.40.1

---

user-demo/Dockerfile
user-demo/package-lock.json
user-demo/package.json

Bump dependencies in user demo

---

docs/adr/0053-do-not-expose-platform-observability-services-to-end-users.md
docs/adr/index.md

adr-0053 Observability data for platform services

---

docs/adr/0053-do-not-expose-platform-observability-services-to-end-users.md

Fixed the broken link with alternative
Quality gates:

adr-0053 fix broken links

---

docs/release-notes/ck8s.md

docs: add apps v0.41.0 release notes

---

docs/operator-manual/disaster-recovery.md

Quality gates:
See: https://github.com/elastisys/compliantkubernetes-apps/pull/2295

Update links to disaster recovery instructions in Apps

---

docs/operator-manual/disaster-recovery.md

Quality gates:
Updated the disaster recovery document:
- Updated commands in the Velero steps to use `ck8s ops velero`
- Added link to Velero docs for changing StorageClass when restoring
- More clarity of cluster context
- Fixed some broken notes by switching to Github Alerts
- Moved some commands from inline to command blocks to be more copy-pasteable

Update Velero disaster recovery instructions

---

docs/release-notes/redis.md

redis: added v7.2.5-ck8s1 release notes

---

docs/user-guide/additional-services/argocd.md

docs: fix argocd links

---

docs/ciso-guide/controls/bsi-it-grundschutz.md
docs/user-guide/ci-cd.md
docs/user-guide/go-live.md
docs/user-guide/maintenance.md
docs/user-guide/safeguards/default-pod-topology-spread-constraints.md
docs/user-guide/safeguards/enforce-networkpolicies.md

Fixed broken links to welkin-user-demo

---

docs/adr/0055-welkin-to-consist-of-both-public-and-private-open-source.md
docs/adr/index.md

ADR-0055 - Welkin to consist of both public and private open source

---

docs/index.md
docs/stylesheets/extra.css
docs/user-guide/alerts.md
docs/user-guide/backup.md
docs/user-guide/ci-cd.md
docs/user-guide/continous-development.md
docs/user-guide/delegation.md
docs/user-guide/demarcation.md
docs/user-guide/deploy.md
docs/user-guide/faq.md
docs/user-guide/go-live.md
docs/user-guide/index.md
docs/user-guide/kubernetes-api.md
docs/user-guide/kubernetes-ui.md
docs/user-guide/log-based-alerts.md
docs/user-guide/logs.md
docs/user-guide/metrics.md
docs/user-guide/namespaces.md
docs/user-guide/network-model.md
docs/user-guide/operate.md
docs/user-guide/prepare-application.md
docs/user-guide/prepare.md
docs/user-guide/registry.md
docs/user-guide/troubleshooting.md
mkdocs.yml

Quality gates:
Address further comments we go during migration, in particular:
- Harmonization of page descriptions.
- Harmonization of text under commercial offer.
- Add a tagline on the first page to describe what Welkin is.

More branding fixes

---

docs/stylesheets/extra.css

Center the sidebar logo properly

---

docs/release-notes/welkin.md

release: Added release notes for apps 0.42.0

---

docs/ciso-guide/index.md
docs/operator-manual/access-control.md
docs/operator-manual/air-gapped.md
docs/operator-manual/break-glass.md
docs/operator-manual/cluster-sizing.md
docs/operator-manual/disaster-recovery.md
docs/operator-manual/ingress.md
docs/operator-manual/maintenance.md
docs/operator-manual/opensearch-mappings.md
docs/operator-manual/schema/config-properties-user-config-properties-alertmanager-config.md
docs/operator-manual/troubleshooting.md
docs/operator-manual/user-alerts.md
docs/operator-manual/user-managed-crds.md
docs/user-guide/prepare-idp.md
docs/user-guide/prepare.md
docs/user-guide/safeguards/enforce-networkpolicies.md

Quality gates:
major changes in this pr:
Changed up the [user-alerts](https://github.com/elastisys/welkin/blob/628a15c8c6fa724f940fd351383289872667ae6e/docs/operator-manual/user-alerts.md) page as it was using a very old version of apps.
Changed the recommendation for Kubespray on the [maintenance](https://github.com/elastisys/welkin/blob/628a15c8c6fa724f940fd351383289872667ae6e/docs/operator-manual/maintenance.md?plain=1#L133-L138) page to upgrade one minor version at a time instead of a patch version at a time, as Kubespray says its okay to [skip patch versions](https://kubespray.io/#/docs/operations/upgrades?id=multiple-upgrades) when upgrading.
Added a step to the Google IdP guide on the [groups …

docs: improve some webpages

---

docs/operator-manual/understand-the-basics.md
mkdocs.yml

Quality gates:
This page clarified the knowledge which is needed to operate Welkin. The page is inspired from a similar page in the [Argo CD](https://argo-cd.readthedocs.io/en/stable/understand_the_basics/) project.

Add Understand the Basics page

---

docs/release-notes/capi.md

docs: add release notes for capi v0.4.0

---

docs/adr/0023-allow-snippets-annotations.md
docs/adr/0056-allow-snippets-annotations-after-risk-acceptance.md
docs/adr/index.md

adr-0056 Only allow Ingress Snippet Annotations after Proper Risk Acceptance
Quality gates:

adr-0056 Only allow Ingress Snippet Annotations after Proper Risk Acceptance

---

docs/user-guide/additional-services/postgresql.md

docs: add note about PGHOST_REPLICA

---

CONTRIBUTING.md
docs/adr/0006-use-standard-kubeconfig-mechanisms.md
docs/adr/0025-local-storage.md
docs/user-guide/understand-the-basics.md
mkdocs.yml

Quality gates:
This PR does two things:
- It fixes comments which were made after [the Vale PR](https://github.com/elastisys/welkin/pull/1004) was merged.
- It acts on feedback from the "Writing Killer Documentation" workshop and adds clear expectations on what the application developer is supposed to know before reading the documentation.

Add understading the basics app dev

---

docs/release-notes/rabbitmq.md

Rabbitmq: Added v3.13.7 release notes

---

overrides/main.html

Quality gates:
Remove the rebranding banner, as previously decided.

Remove banner

---

docs/user-guide/gpu.md
mkdocs.yml

Added page for how to use GPU

---

docs/release-notes/welkin.md

docs: add release notes for apps v0.42.1

---

docs/release-notes/redis.md

redis: Added release notes for redis 7.2.7

---

CODEOWNERS

Quality gates:
Update codeowners to reflect changes to internal goto areas.

all: update codeowners with new goto area updates

---

docs/release-notes/kubespray.md

docs: Add release notes for kubespray v2.26.0-ck8s2

---

.github/workflows/lint.yml
CONTRIBUTING.md
mkdocs.yml
scripts/jsonschema2md.sh

Allows for working on a path to Apps and a more manageable handling of references.
Quality gates:
This is changes needed to be able to use it the test harness in Apps.

scripts: Improve jsonschema2md

---

docs/glossary.md
docs/user-guide/additional-services/redis.md

Redis: Update the breaking URL

---

docs/ciso-guide/audit-logs.md

Add specification and assessment on group accounts

---

docs/request-a-feature.md
docs/user-guide/self-managed-services/index.md
mkdocs.yml

Quality gates:
As discussed previously, we want to encourage customers to request a feature. We also want to encourage application developers to contribute to Welkin, in particular when it comes to supporting new self-managed services. This PR addresses both.
> [!NOTE]
> The marketing team is working with the Jira Service Management to polish the Jira configuration. This PR is written with the desired state in mind and may slightly deviate from the current state.

Show how to request a feature

---

docs/release-notes/welkin.md

docs: added release notes for apps v0.43.0

---

docs/adr/0032-boot-disk-size.md
docs/adr/0058-boot-disk-sizes.md

adr-0058: Boot disk recommended sizes

---

docs/operator-manual/disaster-recovery.md

docs: make opensearch restore commands easier to copy and paste

---

docs/img/compliance.svg

Update compliance overview image.
Quality gates:

Update compliance overview image

---

docs/user-guide/self-managed-services/flux.md
docs/user-guide/self-managed-services/kafka.md

docs: clearer wording for self-managed namespace name

---

docs/user-guide/gpu.md

docs:update the user guide page for gpu

---

docs/release-notes/kubespray.md

docs: added release notes for kubespray v2.26.0-ck8s3

---

docs/quality-criteria.md

Quality gates:
Due to https://github.com/elastisys/compliantkubernetes-apps/pull/2433

docs: Update QA checklist

---

docs/quality-criteria.md

Quality gates:
Updates it for https://github.com/elastisys/compliantkubernetes-kubespray/pull/416

Point to new Kubespray QA checklist

---

docs/user-guide/additional-services/redis.md

Quality gates:
Noticed some note alerts were broken, this PR fixes this. There are still other notes that are in github alert style but I kept them as they were as they were using custom titles.

Fixes to alerts in Redis page

---

docs/operator-manual/disaster-recovery.md

docs: update dr page with SM policy change

---

.editorconfig
.github/pull_request_template.md
.pre-commit-config.yaml
docs/user-guide/go-live.md
docs/user-guide/kubernetes-api.md
docs/user-guide/maintenance.md
docs/user-guide/network-model.md
docs/user-guide/prepare-application.md
docs/user-guide/safeguards/default-pod-topology-spread-constraints.md
docs/user-guide/safeguards/enforce-no-root.md
docs/user-guide/safeguards/enforce-resources.md

Quality gates:
Code snippets reference line numbers. This means that every time we change the user demos, we also need to update the line numbers.
This PR fixes the line numbers which we forgot to update and adds a quality gate, so we won't forget in the future.
I also took this opportunity to improve `.editorconfig` so that vim properly enforces an 80-characters line length in commit messages.
Fixes #608

Fix links to code snippets and add a quality gate

---

docs/release-notes/argocd.md

docs: added release notes for argocd v2.14.3-ck8s1

---

docs/release-notes/welkin.md

docs: add release notes for apps v0.42.2

---

docs/release-notes/welkin.md

docs: add release notes for apps v0.43.1

---

docs/release-notes/welkin.md

docs: add release notes for apps v0.44.1

---

docs/release-notes/welkin.md

docs: add release notes for apps patches v0.42.2, v0.43.1 and v0.44.1

---

docs/user-guide/metrics.md

Quality gates:
PR to reflect [Prometheus v3 which updates the Prometheus UI](https://promlabs.com/blog/2024/09/11/a-look-at-the-new-prometheus-3-0-ui/).
Welkin apps PR for upgrading Prometheus: https://github.com/elastisys/compliantkubernetes-apps/pull/2381

Update metrics page for Prometheus v3 UI

---

docs/user-guide/self-managed-services/kafka.md

Add note about some kafka feature limitations

---

docs/mission-and-vision.md

Quality gates:
Add security principles to the mission and vision. Based on:
- [BDEW Whitepaper](https://www.bdew.de/media/documents/BDEW-OE-VSE-Whitepaper-3.0.pdf)
- [EU CRA](https://eur-lex.europa.eu/eli/reg/2024/2847/oj/eng)

Add security principles to mission and vision

---

docs/release-notes/welkin.md

docs: add release notes for apps v0.45.0

---

docs/operator-manual/access-control.md

docs: added defining access control per namespace

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/operator-manual/air-gapped.md

@llarsson Is this what you expected?
Quality gates:
> [!IMPORTANT]

Add Catalog of air-gapped requirements

---

docs/release-notes/capi.md

docs: Release notes for cluster-api version 0.5.1

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/release-notes/kubespray.md

Added release notes for Kubespray v2.27.0-ck8s1

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/operator-manual/infrastructure-requirements.md
mkdocs.yml
requirements.in

For our Self-Managed offer, it is good to have an initial idea for infrastructure requirements which Welkin needs. We previously had these "hidden" in some internal document, but they should really be more visible.
Quality gates:
> [!IMPORTANT]

Add Infrastructure Requirements

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/operator-manual/runbooks.md
mkdocs.yml

Welkin comes with shareable, but non-public runbooks. Let the whole world know. :smile:
Quality gates:
> [!IMPORTANT]

Add runbooks

---

docs/operator-manual/access-control.md

Quality gates:
> [!IMPORTANT]
Describe how to use Document-level security for fine-grained access control within an index

Add documentation for document-level security in opensearch

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/release-notes/capi.md

docs: Release notes for cluster-api version 0.6.0

---

docs/release-notes/welkin.md

Add missing apps v0.42 patch release notes

---

docs/release-notes/welkin.md

Add missing apps v0.43 patch release notes

---

docs/release-notes/welkin.md

docs: add apps v0.44.2 release notes

---

docs/release-notes/welkin.md

docs: add apps v0.45.1 release notes

---

docs/release-notes/welkin.md

docs: add release notes for new apps patches

---

docs/ciso-guide/controls/cra.md

Sorry @Elias-elastisys . Forgot to push my local branch before submitting the previous PR.
Fixed now for real. :smile:
Quality gates:
> [!IMPORTANT]

Kured is off by default

---

docs/user-guide/how-many-environments.md

Make it clear what limitation exists for cluster isolation when determining how many environments to have.
Quality gates:
> [!IMPORTANT]

Explicitly state multiple workload cluster limitations

---

docs/adr/0004-plan-for-usage-without-wrapper-scripts.md
docs/adr/0005-use-individual-ssh-keys.md
docs/adr/0006-use-standard-kubeconfig-mechanisms.md
docs/adr/0007-make-monitoring-forwarders-storage-independent.md
docs/adr/0009-use-cluster-issuers-for-letsencrypt.md
docs/adr/0012-do-not-persist-dex.md
docs/adr/0015-we-believe-in-community-driven-open-source.md
docs/adr/0016-gid-0-is-okey-but-not-by-default.md
docs/adr/0017-persist-dex.md
docs/adr/0024-allow-Harbor-robot-account.md
docs/adr/0025-local-storage.md
docs/adr/0029-expose-jaeger-ui.md
docs/adr/0030-run-argocd-on-elastisys-nodes.md
docs/adr/0031-run-csi-cinder-controllerplugin-on-elastisys-nodes.md
docs/adr/0032-boot-disk-size.md
docs/adr/0033-run-cluster-api-controllers-on-service-cluster.md
docs/adr/0034-how-to-run-multiple-ams-packages-of-the-same-type.md
docs/adr/0036-run-ingress-nginx-as-daemonset.md
docs/adr/0037-enforce-ttl-on-jobs.md
docs/adr/0038-replace-starboard-operator-with-trivy-operator.md
docs/adr/0039-application-dev-permissions.md
docs/adr/0041-encryption-at-rest.md
docs/adr/0042-argocd-dynamic-hnc-namespaces.md
docs/adr/0045-use-specialised-prebuilt-images.md
docs/adr/0046-handle-crds.md
docs/adr/0047-kubernetes-versions.md
docs/adr/0048-access-management-for-AMS-with-network-policies.md
docs/adr/0050-use-cluster-isolation.md

Like the previous PR, this addresses mostly:
- impedance mismatches between singular/plural
- typos
- punctuation
..but also takes the liberty to add some adverbs
where they make sense.
Quality gates:
> [!IMPORTANT]

docs: fix more typos / grammar / md after proofreading

---

CONTRIBUTING.md
docs/operator-manual/air-gapped.md
docs/operator-manual/common.md
docs/operator-manual/disaster-recovery.md
scripts/jsonschema2md.sh

Quality gates:
> [!IMPORTANT]
Part of elastisys/ck8s-issue-tracker#199

Chore: use yq4 syntax wherever possible

---

docs/release-notes/postgres.md

docs: Add release notes for Welkin PostgreSQL v1.12.2-ck8s2

---

docs/release-notes/rabbitmq.md

Add release notes for Welkin RabbitMQ v4.0.6-ck8s2

---

docs/user-guide/network-model.md

Quality gates:
> [!IMPORTANT]
Documentation for internal load balancers
Part of https://github.com/elastisys/mse-internal-docs/issues/444

docs: internal lb

---

docs/user-guide/network-model.md

docs: fix warning alert

---

docs/ciso-guide/intrusion-detection.md

Fixes #267
Document which Falco rules are enabled by default.
Quality gates:
> [!IMPORTANT]

Document which Falco rulesets

---

docs/user-guide/logs.md

docs: opensearch reporting feature now working

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/user-guide/safeguards/enforce-signed-image-verification.md
mkdocs.yml

docs: add signed image verficiation safeguard

---

.markdownlint-cli2.yaml
.pre-commit-config.yaml

Quality gates:
> [!IMPORTANT]
Because else it prints version, all files, summary, etc, instead of only the files that have errors needed to be fixed.

Make markdownlint less verbose

---

docs/release-notes/rabbitmq.md

Quality gates:
> [!IMPORTANT]
Release notes for new RabbitMQ patch.

Add release notes for Welkin RabbitMQ v4.0.6-ck8s3

---

docs/release-notes/kubespray.md

Add release notes for Welkin Kubespray v2.26.0-ck8s5 and v2.27.0-ck8s2

---

docs/release-notes/valkey.md

Add Valkey 8.0.3 release notes

---

docs/operator-manual/disaster-recovery.md

- [ x ] personal data beyond what is necessary for interacting with this Pull Request;
- [ x ] business confidential information, such as customer names.
Quality gates:
- [ x ] I'm aware of the [Contributor Guide](../CONTRIBUTING.md) and did my best to follow the guidelines.
- [ x ] I'm aware of the [Glossary](../docs/glossary.md) and did my best to use those terms.
> [!IMPORTANT]
- [ x ] I have updated links to …

Add pv/pvc velero configmap

---

docs/release-notes/capi.md

chore: add capi 0.7.0 changelog

---

.markdownlint.yaml
ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/user-guide/additional-services/pgbouncer.md
docs/user-guide/additional-services/postgresql.md
docs/user-guide/additional-services/timescaledb.md
mkdocs.yml

Quality gates:
> [!IMPORTANT]
Documentation for PgBouncer
Requires ck8s-postgresql `v1.13.0-ck8s1` to be released.
Fixes https://github.com/elastisys/compliantkubernetes-postgresql/issues/219
Question for reviewers:
- Should I be louder about the danger of accidentally misconfiguring PgBouncer? Since it can lead to loss of service.

Documentation for PgBouncer

---

docs/operator-manual/user-alerts.md

Fix link, as highlighted by the linkchecker.
Quality gates:
> [!IMPORTANT]

fix: Fix link in user alerts

---

docs/release-notes/capi.md
docs/user-guide/additional-services/pgbouncer.md

fix: correct changelog for CAPI v0.7.0

---

docs/release-notes/welkin.md

Add apps v0.47.0 release notes

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/operator-manual/maintenance.md

Quality gates:
> [!IMPORTANT]
Added a note regarding Welkin advising against rollbacks to instead have staged rollouts and rollforwards if needed.
Also updated the migration steps to rely more on the upstream repos, as they were quite out dated.

Update maintenance doc and add note regarding migration rollbacks

---

docs/release-notes/welkin.md

Add release notes for apps v0.46.1 and v0.47.1

---

docs/release-notes/welkin.md

Quality gates:
> [!IMPORTANT]
Port to main from `release-v0.47` branch.

docs: add release notes for apps v0.47.2 (#1148)

---

docs/release-notes/welkin.md

docs: add release notes for apps v0.48.0

---

docs/user-guide/debug.md
docs/user-guide/operate.md
mkdocs.yml

added debug section

---

ci/vale/styles/config/vocabularies/Elastisys/accept.txt
docs/ciso-guide/controls/bsi-it-grundschutz.md

Add more context around BSI APP.4.4 and Welkin

---

.pre-commit-config.yaml
docs/operator-manual/understand-welkin.md
examples/adminlogs/change/20YY-MM-DD-short-description.md
examples/adminlogs/incident/20YY-MM-DD-short-description.md
examples/adminlogs/maintenance/20YY-MM-DD-short-description.md

Add writing adminlogs section and templates

---

docs/user-guide/logs.md

Fix broken MinIO link

---

docs/operator-manual/common.md

Fixes #1167
Quality gates:
> [!IMPORTANT]

Remove welkin-rook admonition, once we make it public

---

docs/adr/0021-tls-for-additional-services.md

fix(linkchecker): Fix URL in ADR-0021

---

docs/release-notes/capi.md

docs: add release notes for Capi v0.7.2

---

docs/operator-manual/disaster-recovery.md

Quality gates:
> [!IMPORTANT]
Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/574

docs: Added commands to suspend automatic snapshots during disaster recovery.

---

docs/user-guide/prepare.md

Quality gates:
> [!IMPORTANT]
Updated the UI link because OpenLens no longer getting updates.

docs: update the ui choice for kubernetes
