- docs/user-guide/backup.md
- mkdocs.yml
Initial Velero documentation, based on our internal Velero documentation + the official documentation on [velero.io](velero.io).
Judging by all available documentation as well as [an open issue in the Velero repo](https://github.com/vmware-tanzu/velero/issues/504), it's not possible to restore a Persistent Volume without restoring the associated Pod, so I didn't include anything about using GitOps for Resources. That issue might be worth keeping an eye on though, if they end up adding that functionality.
fixes #18
> docs: add velero documentation

- README.md
This commit clarifies the relationship between the
`compliantkubernetes`, `compliantkubernetes-kubespray` and
`compliantkubernetes-apps` repos.
> Point to code

- docs/operator-manual/gcp.md
- mkdocs.yml
Added operator manual for setting up Compliant Kubernetes on GCP using compliantkubernetes-kubespray and compliantkubernetes-apps, using the GCP Persistent Disk Driver for block storage.
Fixes elastisys/compliantkubernetes-kubespray#14 and #58
> docs: add operator manual for GCP

- README.md
- docs/operator-manual/gcp.md
- docs/operator-manual/openstack.md
- mkdocs.yml
This adds a page for Openstack, similar to what we already have for GCP, AWS, Exoscale, etc.
Not quite sure if this fixes #78, but that is at least my intention. I clarified the cloud credentials part for GCP and added them for Openstack of course.
One thing that may not be obvious if how GCP and AWS differ from Openstack. However, I felt this isn't really the correct place for such documentation as it would just echo the upstream. Anyway, to help with the review, here is a summary:
In GCP and AWS, the Nodes themselves have identities and access to the cloud without having to specify credentials for them to use. Openstack, on the other hand, relies on credentials that you give the cloud controller. Therefore we need (separate) credentials for setting up the infrastructure and for passing …
> Add openstack

- docs/operator-manual/exoscale.md
Exoscale docs said to use `$SERVICE_CLUSTER` as the name when creating DNS domains but `<environment_name>` for the domains in the apps config; changed them to both use the latter.
> Exoscale: make created DNS domains consistent with config

- docs/operator-manual/openstack.md
While this is not perhaps exactly what @cristiklein intended, this could at least be a start.
I had some issues while trying to set clusters up on different providers for several reasons, this consumed most of the time for the issue.
- Generated openrc file not setting the appropriate variables for cloud_provider (citycloud).
- Must use `use_access_ip = 0` on citycloud (and probably safespring(old)) when `master_allowed_remote_ips` is set.
- `dns_nameserver` must be set on safespring(old).
- Openstack provider issues, gateway timeouts  and vm's entering a non acceptable state on citycloud, vm's not getting any internet on safespring(new) due to DHCP agent on compute nodes not functioning.
In the end I decided to put minimal cluster.tfvars in the docs that are copy pastable.
fixes #92
> openstack: Add some tf var snippets

- docs/operator-manual/common.md
- docs/operator-manual/exoscale.md
This PR:
- Updates the manual for the v0.15.0 release of `compliantkubernetes-apps`
- Fixes some formatting/spelling and add clarifications for existing steps
- Adds instructions on how to create the required S3 buckets
Fixes https://github.com/elastisys/compliantkubernetes-apps/issues/445
> Exoscale operator manual update to v0.15.0

- docs/operator-manual/troubleshooting.md
We slowly seem to converge to a standardized config folder structure,
which can be observed both in the ops config repo and in the
soon-to-be-public ck8s-devbox. I adjusted the troubleshooting guide to
match this config folder structure.
> Move inventory.ini

- docs/operator-manual/troubleshooting.md
I have now fully processed what Simon said back [here](https://github.com/elastisys/compliantkubernetes/pull/130#discussion_r645469221). :smile:
> I think you're right that it's a good mental check to manually change directory to know what you are working on. However, terraform devs seem to think you should have a separate module configuration for each cluster in that case. In v0.15.0 not running from the root module is going to become deprecated and you will have to use a -chdir flag if you want to keep running from elsewhere.
>
> I believe this also makes automatic pickup of terraform.tfstate not working anymore if it's not located in the root module path. Haven't confirmed this though.
Terraform v0.15.0 does not take the root module as argument anymore.
Instead, it expects to always …
> Prepare for Terraform v0.15.0

- docs/operator-manual/openstack.md
Added a clarification as to what kube_oidc_url should be set to.
> docs: clarified kube_oidc_url

- docs/operator-manual/aws.md
While working on another project I have verified that the manual is working fine for v0.17.0.
> Update AWS operator manual to v0.17.0

- docs/operator-manual/aws.md
- docs/operator-manual/clean-up.md
This PR improves Teardown documentation by:
- fixing formatting
- adding clarification that one should run `clean` scripts even when removing the whole infrastructure
> Improve teardown docs

- docs/operator-manual/openstack.md
This PR documents the finding of: [#497](https://github.com/elastisys/ck8s-ops/issues/497)
Unfortunately it only worked for safespring.
Added information about using application credentials when running cluster on safesrping with kubespray version v2.17.0+.
> Openstack use application credentials safespring

- docs/operator-manual/openstack.md
This adds the default configuration for Cinder on Openstack, along with some notes about the options.
> Add Cinder CSI default configuration on Openstack

- docs/release-notes.md
Anything else in [the changelog](https://github.com/elastisys/compliantkubernetes-apps/blob/main/CHANGELOG.md#v0180---2021-10-28) that seems worth mentioning in these release notes?
> Add release notes for apps version 0.18.0

- docs/index.md
- overrides/main.html
See below screenshot:
- "Elastisys Compliant Kubernetes(R)" is written on the first page.
- Kubernetes is properly acknowledged as a trademark on the footer of every page.
> Make trademark usage more prominent

- docs/compliantkubernetes/user-guide/go-live.md
- docs/compliantkubernetes/user-guide/prepare.md
- user-demo/deploy/ck8s-user-demo/templates/deployment.yaml
- user-demo/deploy/ck8s-user-demo/values.yaml
Recommend replication 2 and topologySpreadConstraints, so that the
application tolerates single Node failure by default. Provide an option
to allow the application to tolerate single Zone failures.
@Pavan-Gunda Please check if this is in line with what we discussed the application needs to do to tolerate Node reboots.
Fixes #207
> User demo now tolerates Node failure and reboot

- docs/compliantkubernetes/release-notes.md
I added the Grafana security fix in the release log
> releaselog: updated with grafana security fix

- docs/compliantkubernetes/tech-radar/index.html
Keeping Thanos in "trial" ring, until initial implementation is ready, we see more internal adoption and we build more confidence.
> Document arch decision on replacing InfluxDB with Thanos

- docs/compliantkubernetes/user-guide/additional-services/postgresql.md
Added documentation to let the user know they can use TimescaleDB.
Fixes #294 
Did I miss an important step? Are there any (regular PostgreSQL setup) step that is not required to do when using Timescale? Please let me know. :slightly_smiling_face:
> docs: added timescaledb documentation

- docs/compliantkubernetes/user-guide/logs.md
Opensearch reporting function isn't working so we needed some documentation for how customers should do it themselves
> Added documentation for how to export logs

- docs/compliantkubernetes/user-guide/alerts.md
- docs/compliantkubernetes/user-guide/backup.md
- docs/compliantkubernetes/user-guide/setup.md
Removed references to SC and WC in "For Application Developers" part of the docs.
Fixes #339
> docs: remove sc/wc references in 'for AD'

- .pre-commit-config.yaml
- docs/compliantkubernetes/user-guide/network-model.md
- user-demo/deploy/ck8s-user-demo/values.yaml
- user-demo/deploy/oauth2-proxy.yaml
Ingress authentication example via `oauth2-proxy` as asked by a few application developers.
Works out-of-the-box with Compliant Kubernetes, with two minor deviations:
- oauth2-proxy needs resource requests and limits.
- oauth2-proxy image needs to be allowlisted.
Note to reviewers: The link `https://github.com/elastisys/compliantkubernetes/blob/main/user-demo/deploy/oauth2-proxy.yaml` should become available after merging. This is absolute on purpose, to ensure the user is redirected from the public docs to the GitHub project.
> Added Ingress OAuth2 example

- docs/compliantkubernetes/adr/0022-use-dedicated-nodes-for-additional-services.md
- docs/compliantkubernetes/ciso-guide/backup.md
- docs/compliantkubernetes/operator-manual/maintenance.md
- docs/compliantkubernetes/user-guide/additional-services/index.md
- docs/compliantkubernetes/user-guide/backup.md
- docs/compliantkubernetes/user-guide/ci-cd.md
- docs/compliantkubernetes/user-guide/delegation.md
- docs/compliantkubernetes/user-guide/demarcation.md
- docs/compliantkubernetes/user-guide/network-model.md
- docs/compliantkubernetes/user-guide/prepare-application.md
- docs/compliantkubernetes/user-guide/safeguards/enforce-networkpolicies.md
- mkdocs.yml
Fixes #363 
I went through "APP.4.4 Kubernetes" and added "quick wins". They are currently part of the ISO 27001 page, because that is what is easier to do within the documentation project. Happy to fix this in another issues.
There are a few controls that I didn't touch:
- APP.4.4.A1 Planung der Separierung der Anwendungen (B), i.e., "use separate clusters for production and testing", this is something that we should cover in our ToS.
- APP.4.4.A6 Initialisierung von Pods (S), this is something application developers need to do.
- APP.4.4.A11 Überwachung der Container (S), i.e., add liveliness and readiness probes, this is something application developers need to do.
- APP.4.4.A12 Absicherung der Infrastruktur-Anwendungen (S), i.e., infrastructure security, this is an operational …
> Add bsi controls

- docs/compliantkubernetes/release-notes.md
Release notes for the new kubespray version.
> docs: release notes kubespray v2.19.0

- docs/user-guide/long-term-log-retention.md
- mkdocs.yml
I think I might need to add a bit more on the "exporting indices", but I don't know how extensive I should make this.
If I should make one "export to file" example, or some "s3cmd check then upload with the elasticdump" snippet.
Fixes: #371
> Add docs and snippets for setting up long-term log retention

- docs/user-guide/kubernetes-ui.md
@jakubkrzywda just discovered that Lens has turned against its users. :frowning: If you install Lens today, you get an "activation window" (see screenshot), which you cannot get rid of except by creating a Lens ID. It is also said that a lot of tracking happens behind the scene.
The crazy thing is that the whole Lens source code is open-sourced MIT-licensed. So basically the Lens binary = Lens open-source source code + non-features.
Anyway, we need to let our users know.
> Recommend OpenLens

- docs/adr/index.md
Our internal audit revealed that we haven't made it clear that our arch process maps to ISO 27001 A.14.2.4 "Restrictions on Changes to Software Packages".
This patch clarifies it.
> Clarify ISO 27001 A.14.2.4

- docs/operator-manual/on-prem-standard.md
Made some improvements
- Minor spelling and style fixes
- Made commands appear consistent throughout
- Use admonitions instead to make notes and key messages appear prettier
- Suggested domain name configuration for when both service and workload clusters are in the same subnet
> Some improvements to the on-prem documentation

- docs/operator-manual/on-prem-standard.md
Added new items about:
1. How to change the Default Kubernetes Subnet Addresses
2. Change local DNS IP if you change the default kubebernetes subnet address
3. Configure the load balancer IP on the loopback interface for each worker node
> Updated on-prem documentation

- docs/img/git-alt.svg
- docs/stylesheets/extra.css
- overrides/partials/source.html
- requirements.txt
Solves https://github.com/elastisys/marketing/issues/42 by adding a link to the elastisys.com website, using a prominent button-like element in the header.
Desktop view:
Mobile view:
> Link to dotcom

- docs/release-notes/ck8s.md
See [the apps changelog](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.28.0/CHANGELOG.md#v0280---2023-01-20) if you think something more should be added or removed.
> docs: add release notes for apps v0.28.0 (main branch)

- docs/release-notes/ck8s.md
See [the apps changelog](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.28.0/CHANGELOG.md#v0280---2023-01-20) if you think something more should be added or removed.
> docs: add release notes for apps v0.28.0 (release branch)

- docs/user-guide/kubernetes-api.md
Found a link that did not work, in the "Step 2: Deploy" page on the docs. Now it should work.
> fix(docs): broken link in deploy demo docs

- user-demo/deploy/ci-cd-role.yaml
Useful to allow the CI-CD pipeline to inspect the success of the deployment, as we recommend in our "starter kit":
https://github.com/elastisys/ck8s-starter-nodejs
> Allow example CI-CD role to read certificates

- docs/user-guide/alerts.md
- docs/user-guide/metrics.md
As the port name will change for prometheus and alertmanager, in the next version of kube-promethus-stack, we said that it mighty be better to use the port for the customer facing documents.
> docs: added the port instead of the name for proxy urls

- docs/operator-manual/credentials.md
- docs/operator-manual/cryptography.md
- mkdocs.yml
As discussed during the arch meeting. We make it official that the Compliant Kubernetes project recommends ECRYPT-CSA's cryptographic recommendations. This is what we mandate at Elastisys. We need this for fulfilling various data protection controls, as shown in the docs.
> Add use of cryptography

- docs/ciso-guide/controls/gdpr.md
- docs/operator-manual/provider-audit.md
- docs/user-guide/backup.md
- docs/user-guide/long-term-log-retention.md
- mkdocs.yml
As requested by Commercial, we are now also mapping GDPR "controls" to Compliant Kubernetes documentation pages.
Adding @simonekman for approval, @llarsson for wordsmithing and @emmasundqvist for awareness.
> Add GDPR controls

- docs/user-guide/additional-services/postgresql.md
Updates the docs to reflect the fact that the port-forward service is just a service name.
Also adds a note on the initial password for their user.
> docs: update portforward notes for postgres

- docs/user-guide/safeguards/enforce-job-ttl.md
- mkdocs.yml
Add a new safeguard page for why we automatically set TTL on jobs.
> add job ttl as safeguard

- docs/release-notes/redis.md
redis-release-note - v6.2.6-ck8s1
> redis-release-note- v6.2.6-ck8s1

- docs/user-guide/self-service-guide/keycloak.md
Looked fine in md, did not render properly in mkdocs.
Previous:
Fixed:
> Fixed small indent issue in Keycloak docs

- docs/user-guide/self-service-guide/ferretdb.md
Deployment manifest for FerretDB was missing resource requests which is enforced in CK8s.
> Add resource requests to ferretdb deployment manifest

- docs/stylesheets/extra.css
The latest Firefox (103) has the `:has()` pseudo-class disabled behind a feature flag. Therefore, our previous CSS selectors didn't work on Firefox.
This commit avoids needing to use `:has()`. On the downside, external links from images are only selected when present in the header.
https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility
Fixes #594
> Fix: Highlight external links with Firefox

- docs/operator-manual/troubleshooting.md
Updated troubleshooting guide to follow newer way of interacting with Compliant Kubernetes.
Since ck8s-apps does not support multiple workload clusters this was simply removed and simplified.
> Various fixes to troubleshooting guide

- mkdocs.yml
At least the Troubleshooting page (for Administrators) is in desperate need of a Table of Contents to help navigation.
Before:
After:
> Re-add the Table-of-Contents on the right sidebar

- docs/user-guide/go-live.md
Found some links in the [go-live checklist](https://elastisys.io/compliantkubernetes/user-guide/go-live/) page which were not up to date with the current version of the user-demo Helm chart. This PR should fix these.
> Fix user-demo links in go-live doc

- docs/user-guide/kubernetes-ui.md
- mkdocs.yml
This PR configures the `pymdownx.snippets` plugin to check that the included snippets actually exist -- to my surprise, this is not on by default. It also fixes two snippets paths.
> Fix snippets paths

- docs/user-guide/alerts.md
Clarified how users can silence alerts and that silences created in the UI are not persisted if alertmanager restarts.
> docs: clarify how users silence alerts

- docs/ciso-guide/controls/gdpr.md
- docs/ciso-guide/controls/hipaa.md
- docs/ciso-guide/controls/hslf-fs-201640.md
- docs/ciso-guide/controls/iso-27001.md
- docs/ciso-guide/controls/msbfs-20207.md
- docs/user-guide/additional-services/timescaledb.md
- docs/user-guide/deploy.md
- docs/user-guide/operate.md
- docs/user-guide/prepare.md
- docs/user-guide/self-managed-services/ferretdb.md
- docs/user-guide/self-managed-services/keycloak.md
mkdocs-include-markdown-plugin recently changed the way it resolves paths. Specifically:
```
- Local files:
- Absolute paths (starting with a path separator).
- Relative from the file that includes them (starting with `./` or `../`).
- Relative from the _docs/_ directory. 
```
Hence a path like `_common.include` is now interpreted as relative to the _docs/_ directory.
This commit adds `./` in front of all paths, so that they are correctly interpreted as relative to the file where the include macro is used.
Further reading:
- https://github.com/mondeja/mkdocs-include-markdown-plugin/commit/eb9f6ed90d8da15bf2e23b9b88dced2d8f5391f6#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> Fix include path

- docs/user-guide/prepare-idp.md
- mkdocs.yml
Fixes #584
Fixes #517
I moved the "Configure your IdP" page from elastisys.com to elastisys.io. I basically copy-pasted David's original page and made the following modifications:
- I tried to stick to project voice and our agreed vocabulary, while still pointing Managed Services customers in the right direction.
- I added a bit of info about generic OpenID connectors.
Let me know if this is the right place to put the page in the navbar and if the content is the one we need.
> Move IdP info to elastisys.io

- docs/operator-manual/on-prem-standard.md
We now have a "Prepare your Identity Provider (IdP)" page on elastisys.io, which nicely integrates with the rest of product documentation. Let's use that instead of linking to the deprecared post on elastisys.com.
> Link to "Prepare your IdP" page

- .codespellignore
- .codespellrc
- .github/workflows/lint.yml
- .pre-commit-config.yaml
Because I'm tired of fixing spelling issues *after* I've pushed changes. :sweat_smile: 
And this is also the method we use everywhere else.
> Use codespell on pre-commit

- docs/operator-manual/troubleshooting.md
Found that some commands had trailing `'`. Also updated the instructions for deploying the `rook-toolbox` deployment to make it more "copy-pasteable". One **concern** is that it seems like [rook is going to be deployed with helmfile in the future](https://github.com/elastisys/compliantkubernetes-kubespray/commit/bdfe884e4470f0ddf2501b834feeaf736dda7ec4), thus the instruction for deploying the toolbox may need an update soon, unless this PR should prepare for it already?
> Fix faulty commands in operator-manual troubleshooting

- .gitignore
- mkdocs.yml
- requirements.txt
I just discovered that `mkdocs-material`, the tech that fuels `elastisys.io`, includes a social plugin. Said plugin can generate a social card for each page, which includes our logo, the page title and page description.
I'm copy-pasting some examples below.
If we want to background image then we need to sponsor mkdocs-material with at least $125/months. I feel that no background image is good enough for now, and we should revisit sponsorship later.
What do you think?
> Add social cards

- docs/adr/0002-use-kubespray-for-cluster-lifecycle.md
- docs/adr/0007-make-monitoring-forwarders-storage-independent.md
- docs/adr/0008-use-hostnetwork-or-loadbalancer-for-ingress.md
- docs/adr/0011-let-upstream-projects-handle-crds.md
- docs/adr/0013-configure-alerts-in-omt.md
- docs/adr/0021-tls-for-additional-services.md
- docs/ciso-guide/faq.md
- docs/index.md
- docs/operator-manual/clock-synchronization.md
- docs/operator-manual/getting-started.md
- docs/operator-manual/ingress.md
- docs/operator-manual/maintenance.md
- docs/operator-manual/troubleshooting.md
- docs/user-guide/additional-services/redis.md
- docs/user-guide/delegation.md
- docs/user-guide/demarcation.md
- docs/user-guide/faq.md
- docs/user-guide/metrics.md
- docs/user-guide/prepare.md
- mkdocs-ciso-controls/ciso_controls/__init__.py
- mkdocs-ciso-controls/setup.py
- mkdocs.yml
linkchecker changed its default behavior to warn if a link points to a redirect, i.e., HTTP 30x. [1]. As a result, we got 61 warnings during external link checking. [2]
Instead of disabling the warnings, I decided to go ahead and incrementally fix them. This PR represents the first increment.
Most of those warnings are "forgot to put a slash at the end" warnings.
[1]: https://github.com/linkchecker/linkchecker/commit/beaf9399f88c1d2e6c13f8ff14f54a304eda3c91
[2]: https://github.com/elastisys/compliantkubernetes/actions/runs/6233244612/job/16918039321
> Avoid some redirects

- docs/glossary.md
Microsoft renamed Azure Active Directory to Microsoft Entra ID. The old link to Azure Active Directory is now a redirect.
@davidumea @llarsson @aarnq How should we deal when URLs change with a proper redirect?
I see the following options (please vote or propose another option):
1. As today, issue a PR with reviewers.
- Good, because it raises awareness to everyone.
- Good, because it respects our processes.
- Bad, because it grabs a lot of attention for little value.
2. Bypass PR and fix link directly on `main`.
- Good, because it creates less attention noise.
- Bad, because it bypasses our processes.
3. Let's silence redirect warnings.
- Good, because it reduces attention noise.
- Good, because it respects our processes.
- Bad, because we miss out on interesting signals from the …
> Fix link to Microsoft's IdP

- docs/user-guide/alerts.md
Now I don't have a Mac to test with but I was told that it didn't work with the arguments to `base64` so I added it as a second example.
> Fix example to configure alertmanager

- linkchecker.conf
Permanently fixes pipeline failures, like [this one](https://github.com/elastisys/compliantkubernetes/actions/runs/6624459612/job/17993479875#step:4:26).
Whoever disagrees with this PR is free to take responsibility to fixing 301 and 302 on `elastisys.io`. I did it 5 times in October alone. :smile: 
> Ignore redirect warnings

- overrides/main.html
As per request from analytics partner, this PR replaces the Matomo script loader with the Matomo Tag Manager script loader. This enables one to configure more Matomo-related things directly via Matomo, I believe.
> Replace inline Matomo with its tag manager

- docs/adr/0030-run-argocd-on-elastisys-nodes.md
- docs/ciso-guide/nis2.md
There is a typo in the [Run ArgoCD on the Elastisys nodes](https://elastisys.io/compliantkubernetes/adr/0030-run-argocd-on-elastisys-nodes/) and some linting issues. This PR solves it. 
> Fix typo in argocd related docs

- docs/operator-manual/maintenance.md
The changelog URL changed as a result of [this commit](https://github.com/elastisys/compliantkubernetes-apps/commit/49d066dcb628a3d43ed21c62a09981616284818a). I don't usually buzz people with PRs on fixing links, but in this case I want to make sure I understood the intention going forward correctly.
Thanks for reviewing and confirming!
> Fix: change link to changelog (pun intended)

- CONTRIBUTING.md
- docs/operator-manual/common.md
- docs/operator-manual/maintenance.md
- docs/operator-manual/on-prem-standard.md
Since the apps and kubespray scripts have been modified in recent releases so that certain commands now take an argument (e.g. `ck8s init` now needs to run with a cluster argument: `ck8s init both`), this PR addresses these changes in the public docs. This PR also looks to force wc and sc cluster names which has also been updated in the ck8s apps and kubespray repos.
The on-prem template has been refactored to use the `common.md` to try and have a standard file for how ck8s-apps should be deployed, in which the on-prem template can extend upon.
Some other various fixes have been added in this PR as well, such as removing deprecated code, changing some markdown alerts that better match the text flavor, and extending …
> Update docs with recent ck8s release changes

- docs/user-guide/cluster-api.md
- mkdocs.yml
This will add documentation about what changes an app dev can expect when we later migrate to cluster api.
The idea would be to later migrate these sections into more suitable pages, e.g. the section about egress traffic into 'Network Model', when we start to migrate clusters. There should likely be a period of overlap where the info exists in both places.
> docs: add cluster api migration docs

- docs/operator-manual/access-control.md
> Update adminstrator access control document

- docs/user-guide/additional-services/postgresql.md
Current link to ToS appendix on PostgreSQL doesn't work since it has changed name. This updates the link so that it correctly links to the appendix.
> Fixed a broken link to ToS on PostgreSQL page

- docs/user-guide/alerts.md
- docs/user-guide/operate.md
- Removed the section stating that you need to contact an administrator to activate Alertmanager as this is not the case anymore since it is enabled by default:
https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/wc-config.yaml#L46
- Fixed capitalization inconsistencies for how to write `Alertmanager`, now it adheres to the official way seen in the docs at https://github.com/prometheus/alertmanager
> update Alertmanager docs

- requirements.txt
Quality gates:
Added setuptools to requirements.
Fixes a bug where pkg_resources module isn't installed in venv and crashes on some versions of python.
> Updated requirements to include setuptools

- .github/workflows/deploy.yml
- .gitignore
- .pre-commit-config.yaml
- CONTRIBUTING.md
- docs/operator-manual/schema/README.md
- docs/operator-manual/schema/config.md
- docs/operator-manual/schema/secrets.md
- mkdocs.yml
- package-lock.json
- package.json
- scripts/jsonschema2md.sh
Quality gates:
Adds auto-generate docs from the JSON schemas in Apps.
_Since it currently generates 646 files I'm just gonna let this be a thing in the deployment workflow, with optional steps to view it locally._
To test it out:
> [!important]
> You need to have `yq` version 4 installed as `yq`.
```bash
npm install
./scripts/jsonschema2md.sh
mkdocs serve
```
And then it should be available under:
- "For Platform Administrators"
- "Configuration Reference" 
- "Index" 
- "Config"
- "Secrets"
> [!tip]
> To preview for another branch in Apps set the env `GITHUB_REF_NAME` to the name of the branch.
If you set `release-vX.Y` it should do the _release flow_.
So this _should just work_ for releases but we'll have to see …
> Auto-generate docs from JSON schema

- docs/operator-manual/disaster-recovery.md
Part of elastisys/mse-internal-docs#61
I wanted to simplify the disaster recovery documentation a bit by removing a somewhat awkward back-reference in the OpenSearch section. This should make it flow a bit better.
> docs: remove back-referencing in opensearch DR docs

- docs/img/marchitecture.svg
We accidentally change the marchitecture diagram, with a different diagram.
This reverts commit e29bc1a438addd17da0ce04fed0b5fde4bbd6ebc.
Quality gates:
> Revert "New design as per new brand book"

- docs/adr/0051-open-cert-manager-netpols.md
- docs/adr/index.md
Quality gates:
Add the decision on cert-manager.
Note: I realise that we don't actually give cert-manager `0.0.0.0:443/tcp` by default in apps config, rather when we configure it we do set it to `0.0.0.0:443/tcp` as that is required to communicate to Let's Encrypt.
So, should I add that this is plainly recommendation, and the standard practice for us?
Or should we make it the default for prod and dev flavours, and leave it to be set explicitly in air-gapped?
> adr: open cert-manager netpols

- docs/user-guide/metrics.md
Quality gates:
Added info about default scrape interval and timeout. A user recently asked a question about this.
> docs: add default scrape interval and timeout

- linkchecker.conf
- requirements-linkchecker.txt
Also upgraded linkchecker to 10.5.0 to gain access to the `ignorewarningsforurls` feature.
See release notes:
- https://github.com/linkchecker/linkchecker/releases/tag/v10.5.0
Quality gates:
> Ignore http-rate-limited for stackoverflow.com

- docs/adr/0054-allow-write-access-to-endpoints-and-endpointslices-after-risk-acceptance.md
- docs/adr/index.md
> adr-0054 Allow Application Developer write access to Endpoints and EndpointSlices after Proper Risk Acceptance

- mkdocs.yml
Quality gates:
Fixes the following mkdocs warning:
```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav"
configuration:
- ciso-guide/information-security/index.md
```
> Add Information Security page to nav

- docs/user-guide/list-of-non-functional-application-requirements.html
- docs/user-guide/prepare-application.md
- mkdocs.yml
- scripts/requirements-tsv-to-table.py
Quality gates:
Screenshot below:
> Add non-functional application requirements

- docs/release-notes/postgres.md
Quality gates:
---
First update to the public release notes for postgres for a long time.
I added a note on the fact that this page has not been updated properly and that there is work to improve the release notes for additional managed services (postgres in this case)
> docs: add postgres v1.12.2-ck8s1 release notes

- docs/user-guide/cluster-api.md
Quality gates:
Application Developer applications could potentially block the cluster autoscaler from downscaling nodes. This PR adds a warning notice about this in the Cluster API documentation.
Related to https://github.com/elastisys/ck8s-issue-tracker/issues/313
> Add CAPI cluster autoscaling warning

- docs/stylesheets/extra.css
- overrides/main.html
Quality gates:
I added a banner on the whole site explaining the changes that are going to occur when we move from Compliant Kubernetes to welkin.
This is how the banner looks:
The banner is also only on the top of the page so it goes away if you scroll down:
> docs: add a banner about ck8s change to welkin

- docs/ciso-guide/log-review.md
Quality gates:
Small update to the log review process to potentially catch excessive amount of logs. This could as an example help us update our audit log policy instead of scaling up a bunch of Opensearch volumes.
> docs: check amount of logs in reviews

- user-demo/deploy/welkin-user-demo/values.yaml
Quality gates:
When installing the demo application according to [this section](https://elastisys.io/welkin/user-guide/kubernetes-api/#deploy-user-demo) the deployment will result in a warning about it not following the `restricted` PSS. 
```
$ helm upgrade --install ...
.
.
.
W1107 13:24:08.331340  347415 warnings.go:70] would violate PodSecurity "restricted:latest": 
allowPrivilegeEscalation != false (container "welkin-user-demo" must set securityContext.allowPrivilegeEscalation=false), 
unrestricted capabilities (container "welkin-user-demo" must set securityContext.capabilities.drop=["ALL"]), 
runAsNonRoot != true (pod or container "welkin-user-demo" must set securityContext.runAsNonRoot=true), 
seccompProfile …
```
> Updated helm install example to use proper security defaults

- docs/operator-manual/disaster-recovery.md
Quality gates:
Adds disaster recovery instructions for restoring volumes that don't yet have a
`Pod`, because Velero waits until a Pod mounts the volume before restoring
data.
> Instructions for expedited restoration of WaitForFirstConsumer volumes

- docs/adr/0036-run-ingress-nginx-as-daemonset.md
> adr-0036: Add as benefit the use of externalTrafficPolicy=local

- docs/operator-manual/common.md
Quality gates:
With https://github.com/elastisys/compliantkubernetes-apps/pull/2250, the diagnostics script usage changed how it normally gets its fingerprints to use for encrypting the diagnostics files. This PR addresses this.
> Update diagnostics script usage

- docs/user-guide/self-managed-services/kafka-files/deployment/kafka-operator-deployment.yaml
- docs/user-guide/self-managed-services/kafka-files/kafka-cluster/persistent-single.yaml
- docs/user-guide/self-managed-services/kafka-files/kafka-testing/kafka-consumer.yaml
- docs/user-guide/self-managed-services/kafka-files/kafka-testing/kafka-producer.yaml
- docs/user-guide/self-managed-services/kafka.md
Quality gates:
I was testing self-managed Kafka and noticed some URLs were broken.
I also tested following the instruction with the most recent Kafka operator release v0.44 and from basic testing it worked fine.
> Update self-managed Kafka to v0.44 & fix broken URLs

- docs/operator-manual/understand-welkin.md
- mkdocs.yml
Quality gates:
While drafting an operations manual for a customer, we realized that we don't really have for the platform administrator a page which describes the "forest" before describing the "trees". This PR bridges this gap.
> Understand welkin

- docs/adr/0057-why-we-do-not-use-cloud-managed-kubernetes-services.md
> adr-0057: Why we don't use cloud-managed kubernetes services

- docs/operator-manual/disaster-recovery.md
Quality gates:
In our DR exercise we found the velero restore part to have a lot of text when most of the time all you need from it is a simple command, so i'm trying to make that a little more clear. Also we'd like to mention that one should restore sc before wc, to avoid some minor head scratching when restored wc applications are failing because harbor isn't yet restored.
> docs: improve velero restore

- docs/user-guide/additional-services/rabbitmq.md
Quality gates:
As title suggested, add instruction for application developers to use correct labels on pods to be allowed access to rabbitmq cluster.
> add rule for application access after rabbitmq network policy update

- ci/vale/styles/config/vocabularies/Elastisys/accept.txt
- docs/user-guide/safeguards/enforce-restricted-pod-disruption-budgets.md
- mkdocs.yml
Quality gates:
> [!IMPORTANT]
This adds documentation for a new safeguard regarding restricting the use of PodDisruptionBudgets.
The implementation is done in https://github.com/elastisys/compliantkubernetes-apps/pull/2459 
There you can find a lot more details on why and how this was implemented.
> docs: add safeguard for restricting PDBs

- mkdocs-ciso-controls/ciso_controls/__init__.py
- mkdocs-ciso-controls/setup.py
ISO 27001:2022 has a control which should point to GDPR. We want to capture this by assigning the GDPR page -- which is a tag index page -- the 'ISO 27001 Annex A 5.34 Privacy and Protection of PII' tag.
Due to a logic mistake, a tag on a tag index page would not be properly processed.
See https://github.com/elastisys/welkin/actions/runs/14126181416/job/39575670777#step:5:582 for even more details.
Quality gates:
> [!IMPORTANT]
> You can find such links with `egrep -R …
> Fix: tag not showing up in tags index page

- mkdocs-ciso-controls/ciso_controls/__init__.py
- user-demo/package-lock.json
Previously the CISO pages would take the title from the nav, which are purposefully short (e.g., "Troubleshooting"). Instead, take the title from the Markdown document, which are longer (e.g., "Troubleshooting for Platform Administrators").
Before:
> ISO 27001 Annex A 5.24 Information Security Incident Management Planning and Preparation
> - Troubleshooting
> - Troubleshooting
After:
> ISO 27001 Annex A 5.24 Information Security Incident Management Planning and Preparation
> - Troubleshooting for Platform Administrators
> - Troubleshooting for Application Developers
Also: Update some dependencies in the user-demo.
Quality gates:
> [!IMPORTANT]
> If you changed the …
> Prefer title from markdown

- docs/adr/0050-use-cluster-isolation.md
- docs/adr/0053-do-not-expose-platform-observability-services-to-end-users.md
- docs/operator-manual/break-glass.md
- docs/operator-manual/credentials.md
- docs/operator-manual/maintenance.md
- docs/operator-manual/on-prem-standard.md
- docs/operator-manual/provider-audit.md
- docs/operator-manual/understand-welkin.md
Addresses mishaps spotted during proofreading and
also acts as a proof *of* reading:
- singular/plural mismatches
- missing 'd' in past tense
- missing 's' in present tense, 3rd person
- remove extra indentation from code blocks that resulted in extra "```language" lines being rendered
- BLaaS -> BSaaS
Quality gates:
> [!IMPORTANT]
> Docs: fix typos / grammar / markdown markup after proofreading

- .github/workflows/deploy.yml
We rebranded from ck8s and compliantkubernetes to Welkin 6 months ago. Time to remove those old URLs.
Quality gates:
> [!IMPORTANT]
> Remove pre-branding URLs

- docs/operator-manual/disaster-recovery.md
Quality gates:
> [!IMPORTANT]
Some clarifications for the velero disaster recovery documentation. I also removed a note for an old version of Welkin.
> docs: some clarifications on the velero restore section

- docs/user-guide/namespaces.md
- docs/user-guide/self-managed-services/flux.md
- docs/user-guide/self-managed-services/kafka.md
Quality gates:
> [!IMPORTANT]
---
Since HNC plugin can no longer be installed with krew. I've removed the instructions for how to create and remove sub-namespaces with the plugin and replaced with instructions with yaml instead.
> removed hnc plugin instructions and replaced with yaml

- docs/operator-manual/common.md
Quality gates:
> [!IMPORTANT]
Changed a reference to the rook folder in `compliantkubernetes-kubespray` repo to point to the new `welkin-rook` repo instead.
> docs: change references to rook repository

- overrides/main.html
It seems like robots (e.g., Google Search) struggle to understand that some of our pages are superseded. This leads to bad search results and also inaccurate information in Gemini.
This PR helps robots avoid superseded pages.
Quality gates:
> [!IMPORTANT]
> feat: Help robots avoid superseded pages

- docs/operator-manual/disaster-recovery.md
Quality gates:
> [!IMPORTANT]
Removed the --insecure flag for our OpenSearch Disaster Recovery docs since it's not needed.
> removed --insecure flag for opensearch DR docs

- scripts/jsonschema2md.py
Previously the whole configuration key was a link, which raised the expectation that clicking on it would lead somewhere. Use the permalink marker to make it more obvious that these are just links to the configuration key itself.
Quality gates:
> [!IMPORTANT]
> chore(config reference): Make permalinks more obvious

- docs/operator-manual/air-gapped.md
- docs/operator-manual/getting-started.md
> chore(linkchecker): Fix links to Ubuntu manpages
